// Code generated by protoc-gen-go.
// source: organizations.proto
// DO NOT EDIT!

/*
Package organizations is a generated protocol buffer package.

It is generated from these files:
	organizations.proto

It has these top-level messages:
	Organization
	ListOrganizationsRequest
	ListOrganizationsResponse
	GetOrganizationRequest
	CreateOrganizationRequest
	UpdateOrganizationRequest
	DeleteOrganizationRequest
*/
package organizations

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Organization struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Organization) Reset()                    { *m = Organization{} }
func (m *Organization) String() string            { return proto.CompactTextString(m) }
func (*Organization) ProtoMessage()               {}
func (*Organization) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Organization) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListOrganizationsRequest struct {
	PageSize  int32  `protobuf:"varint,2,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListOrganizationsRequest) Reset()                    { *m = ListOrganizationsRequest{} }
func (m *ListOrganizationsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationsRequest) ProtoMessage()               {}
func (*ListOrganizationsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListOrganizationsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOrganizationsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListOrganizationsResponse struct {
	Organizations []*Organization `protobuf:"bytes,1,rep,name=organizations" json:"organizations,omitempty"`
	NextPageToken string          `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListOrganizationsResponse) Reset()                    { *m = ListOrganizationsResponse{} }
func (m *ListOrganizationsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOrganizationsResponse) ProtoMessage()               {}
func (*ListOrganizationsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListOrganizationsResponse) GetOrganizations() []*Organization {
	if m != nil {
		return m.Organizations
	}
	return nil
}

func (m *ListOrganizationsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetOrganizationRequest struct {
	OrganizationId int64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
}

func (m *GetOrganizationRequest) Reset()                    { *m = GetOrganizationRequest{} }
func (m *GetOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOrganizationRequest) ProtoMessage()               {}
func (*GetOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetOrganizationRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

type CreateOrganizationRequest struct {
	Organization *Organization `protobuf:"bytes,1,opt,name=organization" json:"organization,omitempty"`
}

func (m *CreateOrganizationRequest) Reset()                    { *m = CreateOrganizationRequest{} }
func (m *CreateOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOrganizationRequest) ProtoMessage()               {}
func (*CreateOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateOrganizationRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type UpdateOrganizationRequest struct {
	OrganizationId int64         `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	Organization   *Organization `protobuf:"bytes,2,opt,name=organization" json:"organization,omitempty"`
}

func (m *UpdateOrganizationRequest) Reset()                    { *m = UpdateOrganizationRequest{} }
func (m *UpdateOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateOrganizationRequest) ProtoMessage()               {}
func (*UpdateOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateOrganizationRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *UpdateOrganizationRequest) GetOrganization() *Organization {
	if m != nil {
		return m.Organization
	}
	return nil
}

type DeleteOrganizationRequest struct {
	OrganizationId int64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
}

func (m *DeleteOrganizationRequest) Reset()                    { *m = DeleteOrganizationRequest{} }
func (m *DeleteOrganizationRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteOrganizationRequest) ProtoMessage()               {}
func (*DeleteOrganizationRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteOrganizationRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func init() {
	proto.RegisterType((*Organization)(nil), "organizations.Organization")
	proto.RegisterType((*ListOrganizationsRequest)(nil), "organizations.ListOrganizationsRequest")
	proto.RegisterType((*ListOrganizationsResponse)(nil), "organizations.ListOrganizationsResponse")
	proto.RegisterType((*GetOrganizationRequest)(nil), "organizations.GetOrganizationRequest")
	proto.RegisterType((*CreateOrganizationRequest)(nil), "organizations.CreateOrganizationRequest")
	proto.RegisterType((*UpdateOrganizationRequest)(nil), "organizations.UpdateOrganizationRequest")
	proto.RegisterType((*DeleteOrganizationRequest)(nil), "organizations.DeleteOrganizationRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Organizations service

type OrganizationsClient interface {
	List(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error)
	Get(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*Organization, error)
	Create(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*Organization, error)
	Update(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*Organization, error)
	Delete(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type organizationsClient struct {
	cc *grpc.ClientConn
}

func NewOrganizationsClient(cc *grpc.ClientConn) OrganizationsClient {
	return &organizationsClient{cc}
}

func (c *organizationsClient) List(ctx context.Context, in *ListOrganizationsRequest, opts ...grpc.CallOption) (*ListOrganizationsResponse, error) {
	out := new(ListOrganizationsResponse)
	err := grpc.Invoke(ctx, "/organizations.Organizations/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Get(ctx context.Context, in *GetOrganizationRequest, opts ...grpc.CallOption) (*Organization, error) {
	out := new(Organization)
	err := grpc.Invoke(ctx, "/organizations.Organizations/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Create(ctx context.Context, in *CreateOrganizationRequest, opts ...grpc.CallOption) (*Organization, error) {
	out := new(Organization)
	err := grpc.Invoke(ctx, "/organizations.Organizations/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Update(ctx context.Context, in *UpdateOrganizationRequest, opts ...grpc.CallOption) (*Organization, error) {
	out := new(Organization)
	err := grpc.Invoke(ctx, "/organizations.Organizations/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *organizationsClient) Delete(ctx context.Context, in *DeleteOrganizationRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/organizations.Organizations/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Organizations service

type OrganizationsServer interface {
	List(context.Context, *ListOrganizationsRequest) (*ListOrganizationsResponse, error)
	Get(context.Context, *GetOrganizationRequest) (*Organization, error)
	Create(context.Context, *CreateOrganizationRequest) (*Organization, error)
	Update(context.Context, *UpdateOrganizationRequest) (*Organization, error)
	Delete(context.Context, *DeleteOrganizationRequest) (*google_protobuf1.Empty, error)
}

func RegisterOrganizationsServer(s *grpc.Server, srv OrganizationsServer) {
	s.RegisterService(&_Organizations_serviceDesc, srv)
}

func _Organizations_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOrganizationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organizations.Organizations/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).List(ctx, req.(*ListOrganizationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organizations.Organizations/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Get(ctx, req.(*GetOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organizations.Organizations/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Create(ctx, req.(*CreateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organizations.Organizations/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Update(ctx, req.(*UpdateOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Organizations_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOrganizationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OrganizationsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/organizations.Organizations/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OrganizationsServer).Delete(ctx, req.(*DeleteOrganizationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Organizations_serviceDesc = grpc.ServiceDesc{
	ServiceName: "organizations.Organizations",
	HandlerType: (*OrganizationsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Organizations_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Organizations_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Organizations_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Organizations_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Organizations_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "organizations.proto",
}

func init() { proto.RegisterFile("organizations.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 496 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x94, 0xdb, 0x6a, 0xd4, 0x40,
	0x18, 0xc7, 0x49, 0x56, 0x97, 0xf6, 0xb3, 0xdb, 0xe2, 0x27, 0x94, 0xec, 0x6c, 0x3d, 0x30, 0x52,
	0xbb, 0xec, 0x45, 0x82, 0xf5, 0x4e, 0x2f, 0x64, 0x69, 0x45, 0x0a, 0x82, 0x12, 0x0f, 0x17, 0x8b,
	0x10, 0x52, 0x76, 0x0c, 0xc1, 0x9a, 0x89, 0x9b, 0xa9, 0x68, 0x45, 0x10, 0x41, 0x6f, 0x05, 0x0f,
	0xaf, 0xe2, 0x8b, 0xf8, 0x0a, 0x3e, 0x88, 0x93, 0x49, 0xb3, 0xcc, 0x24, 0x9b, 0x74, 0xc5, 0xab,
	0xdd, 0x7c, 0xa7, 0xf9, 0xcd, 0xff, 0xfb, 0x33, 0x70, 0x89, 0xcf, 0xa2, 0x30, 0x89, 0x4f, 0x42,
	0x11, 0xf3, 0x24, 0x73, 0xd3, 0x19, 0x17, 0x1c, 0x7b, 0x46, 0x90, 0x6c, 0x45, 0x9c, 0x47, 0x47,
	0xcc, 0x0b, 0xd3, 0xd8, 0x0b, 0x93, 0x84, 0x0b, 0xbd, 0x98, 0x0c, 0x4e, 0xb3, 0xea, 0xeb, 0xf0,
	0xf8, 0x85, 0xc7, 0x5e, 0xa5, 0xe2, 0x5d, 0x91, 0xa4, 0x57, 0x60, 0xed, 0xa1, 0x36, 0x0b, 0xd7,
	0xc1, 0x8e, 0xa7, 0x8e, 0x75, 0xcd, 0x1a, 0x76, 0x7c, 0xf9, 0x8f, 0x3e, 0x03, 0xe7, 0x41, 0x9c,
	0x09, 0xbd, 0x26, 0xf3, 0xd9, 0xeb, 0x63, 0x96, 0x09, 0x1c, 0xc0, 0x6a, 0x1a, 0x46, 0x2c, 0xc8,
	0xe2, 0x13, 0xe6, 0xd8, 0xb2, 0xe5, 0xbc, 0xbf, 0x92, 0x07, 0x1e, 0xcb, 0x6f, 0xbc, 0x0c, 0xa0,
	0x92, 0x82, 0xbf, 0x64, 0x89, 0xd3, 0x91, 0xd9, 0x55, 0x5f, 0x95, 0x3f, 0xc9, 0x03, 0xf4, 0x8b,
	0x05, 0xfd, 0x05, 0x83, 0xb3, 0x54, 0xfe, 0x30, 0x1c, 0x83, 0x79, 0x43, 0x09, 0xd4, 0x19, 0x5e,
	0xd8, 0x1d, 0xb8, 0xa6, 0x18, 0x7a, 0xb3, 0x6f, 0x76, 0xe0, 0x0d, 0xd8, 0x48, 0xd8, 0x5b, 0x11,
	0x68, 0x10, 0xb6, 0x82, 0xe8, 0xe5, 0xe1, 0x47, 0x73, 0x90, 0x31, 0x6c, 0xde, 0x67, 0x06, 0x46,
	0x79, 0xbd, 0x1d, 0xd8, 0xd0, 0x47, 0x06, 0x73, 0x5d, 0xd6, 0xf5, 0xf0, 0xc1, 0x94, 0x3e, 0x87,
	0xfe, 0xde, 0x8c, 0x85, 0x82, 0x2d, 0x9a, 0x72, 0x17, 0xd6, 0xf4, 0x72, 0x35, 0xe2, 0x8c, 0x9b,
	0x18, 0x0d, 0xf4, 0xb3, 0x54, 0xea, 0x69, 0x3a, 0x6d, 0x18, 0xbf, 0x2c, 0x64, 0x8d, 0xc3, 0xfe,
	0x57, 0x8e, 0x7d, 0xe8, 0xef, 0xb3, 0x23, 0xf6, 0x7f, 0x18, 0xbb, 0x5f, 0xbb, 0xd0, 0x33, 0x76,
	0x8e, 0x1f, 0x2d, 0x38, 0x97, 0x3b, 0x01, 0x77, 0x2a, 0x2c, 0x4d, 0xbe, 0x23, 0xc3, 0xb3, 0x0b,
	0x0b, 0x1f, 0xd1, 0xed, 0x4f, 0xbf, 0xff, 0x7c, 0xb7, 0xaf, 0xe2, 0x45, 0xef, 0xcd, 0x4d, 0xcf,
	0x68, 0x9a, 0x00, 0xae, 0x9c, 0x06, 0x33, 0xfc, 0x61, 0x41, 0x47, 0x9a, 0x00, 0xb7, 0x2b, 0x83,
	0x17, 0x1b, 0x83, 0xb4, 0x89, 0x46, 0x0f, 0xd4, 0x91, 0x7b, 0x78, 0xbd, 0x76, 0xa4, 0xf7, 0xbe,
	0x22, 0xd1, 0x87, 0xc9, 0x16, 0x92, 0x12, 0xa2, 0x9e, 0xc5, 0x6f, 0x16, 0x74, 0x0b, 0x63, 0x61,
	0xf5, 0xca, 0x8d, 0x7e, 0x6b, 0x87, 0x1b, 0x2b, 0xb8, 0x3b, 0xb4, 0xae, 0xc7, 0x6d, 0x63, 0xd9,
	0x13, 0x87, 0xce, 0xd5, 0x31, 0x33, 0xf8, 0x4b, 0x42, 0x15, 0x76, 0xac, 0x41, 0x35, 0xba, 0xb4,
	0x1d, 0x8a, 0x29, 0xa8, 0x80, 0x2c, 0xa3, 0x58, 0x05, 0x73, 0x44, 0x5a, 0xf4, 0xab, 0x80, 0xff,
	0x94, 0xe0, 0x85, 0x81, 0x6b, 0xe0, 0x8d, 0xbe, 0x26, 0x9b, 0x6e, 0xf1, 0x78, 0xba, 0xe5, 0xe3,
	0xe9, 0xde, 0xcb, 0x1f, 0xcf, 0x72, 0xcb, 0xa3, 0xe5, 0xb6, 0x3c, 0x6a, 0xa1, 0x3c, 0xec, 0xaa,
	0xd1, 0xb7, 0xfe, 0x06, 0x00, 0x00, 0xff, 0xff, 0xad, 0xa7, 0x1d, 0xe2, 0xe9, 0x05, 0x00, 0x00,
}
