steps:
  # Server
#  - name: "gcr.io/cloud-builders/go"
##    env: ["PROJECT_ROOT=server"]
#    args: ["install", "./server"]
#    id: "server-test"
#    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}", "./server"]
    id: "server-docker-build"
    waitFor: ["-"]

  # Compute
#  - name: "gcr.io/cloud-builders/go"
##    env: ["PROJECT_ROOT=compute"]
#    args: ["install", "./compute"]
#    id: "compute-test"
#    waitFor: ["-"]
#
#  - name: "gcr.io/cloud-builders/docker"
#    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}", "./compute"]
#    id: "compute-docker-build"
#    waitFor: ["compute-test"]


images: [
  "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}",
#  "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}",
]
