steps:
  # Server - Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}", "-t", "gcr.io/${PROJECT_ID}/qubit-server:latest", "."]
    id: "server-docker-build"
    dir: "server"
    waitFor: ["-"]

  # Server - Push SHA1
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}"]
    id: "server-docker-push-sha1"
    dir: "server"
    waitFor: ["server-docker-build"]



  # Compute - Build
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}", "-t", "gcr.io/${PROJECT_ID}/qubit-compute:latest", "."]
    id: "compute-docker-build"
    dir: "compute"
    waitFor: ["-"]

  # Compute - Test Unit
  - name: "ubuntu"
    args: ["pwd"]
    env:
      - "GOPATH=."
    id: "compute-docker-test-unit"
    dir: "compute"
    waitFor: ["compute-docker-build"]

  # Compute - Test Integration

  # Compute - Push SHA1
  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}"]
    id: "compute-docker-push-sha1"
    dir: "compute"
    waitFor: ["compute-docker-test-unit"]


  # Compute - Deploy API
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["service-management", "deploy", "compute.pb", "api_config.yaml", "--format", "json", ">", "api-deployment.response.json"]
    id: "compute-deploy-api"
    dir: "compute"
    waitFor: ["compute-docker-push-sha1"]

  # Compute - Deploy - Jinja Template
  - name: "vikingco/jinja2cli"
    args: ["k8s/compute.deployment.yaml", "api-deployment.response.json", ">", "k8s/compute.deployment.formatted.yaml"]
    id: "compute-deploy-api-jinja"
    dir: "compute"
    waitFor: ["compute-deploy-api"]

  # Compute - Deploy - Kubernetes
  - name: "gcr.io/cloud-builders/gcloud"
    entrypoint: "bash"
    args: ["k8s/deploy.sh"]
    dir: "compute"
    waitFor: ["compute-deploy-api-jinja"]


  # Compute - Push Latest
#  - name: "gcr.io/cloud-builders/docker"
#    args: ["push", "gcr.io/${PROJECT_ID}/qubit-compute:latest"]
#    id: "compute-docker-push-latest"
#    dir: "compute"
#    waitFor: "compute-docker-test"

images: []
