steps:
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=server"]
    args: ["install", "."]
    id: "go-install"

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/server:${COMMIT_SHA}", "."]
    id: "docker-build"


images: ["gcr.io/${PROJECT_ID}/server:${COMMIT_SHA}"]
