steps:
  # Server
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}", "-t", "latest", "."]
    id: "server-docker-build"
    dir: "server"
    waitFor: ["-"]

  # Compute
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}", "-t", "latest", "."]
    id: "compute-docker-build"
    dir: "compute"
    waitFor: ["-"]


images: [
  "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}",
  "gcr.io/${PROJECT_ID}/qubit-server:latest",
  "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}",
  "gcr.io/${PROJECT_ID}/qubit-compute:latest",
]
