steps:
  # Server
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=server"]
    args: ["install", "."]
    id: "server-go-install"
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}", "."]
    id: "server-docker-build"
    waitFor: ["server-go-install"]

  # Compute
  - name: "gcr.io/cloud-builders/go"
    env: ["PROJECT_ROOT=compute"]
    args: ["install", "."]
    id: "compute-go-install"
    waitFor: ["-"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}", "."]
    id: "compute-docker-build"
    waitFor: ["compute-go-install"]


images: [
  "gcr.io/${PROJECT_ID}/qubit-server:${COMMIT_SHA}",
  "gcr.io/${PROJECT_ID}/qubit-compute:${COMMIT_SHA}",
]
