version: '2'
services:
  api:
    image: us.gcr.io/qubit-161916/api
    build: ./services/api
    environment:
      - API_SERVICE_ADDRESS=api.qubit.site:9000
      - APP_ENV=development
      - COMPUTE_SERVICE_ADDRESS=compute.qubit.site:9000
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - POSTGRES_URL=postgres://postgres@postgres.api.qubit.site/postgres
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      default:
        aliases:
          - api.qubit.site
    depends_on:
      - postgres
      - compute
  postgres:
    image: postgres:9.6
    networks:
      default:
        aliases:
          - postgres.api.qubit.site

  compute:
    image: us.gcr.io/qubit-161916/compute
    build: ./services/compute
    environment:
      - APP_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      default:
        aliases:
          - compute.qubit.site
