version: '2'
services:
  server:
    image: us.gcr.io/qubit-161916/qubit-server
    build: ./server
    environment:
      - GOOGLE_PROJECT_ID=qubit-161916
      - DATASTORE_PROJECT_ID=qubit-161916
      - DATASTORE_DATASET=qubit
      - DATASTORE_EMULATOR_HOST=datastore:8380
      - DATASTORE_HOST=datastore:8380
      - STORAGE_BUCKET=qubit-dev-161916
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
    ports:
      - 8443:8001
    volumes:
      - ./credentials:/opt/etc/credentials
    depends_on:
      - compute
      - datastore
      - pubsub

  compute:
    image: us.gcr.io/qubit-161916/qubit-compute
    build: ./compute
    environment:
      - GOOGLE_PROJECT_ID=qubit-161916
      - DATASTORE_PROJECT_ID=qubit-161916
      - DATASTORE_DATASET=qubit
      - DATASTORE_EMULATOR_HOST=datastore:8380
      - DATASTORE_HOST=datastore:8380
      - STORAGE_BUCKET=qubit-dev-161916
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
    volumes:
      - ./credentials:/opt/etc/credentials
    depends_on:
      - datastore
      - pubsub

  datastore:
    image: google/cloud-sdk
    environment:
      - CLOUDSDK_CORE_PROJECT=compositor
    command: gcloud beta emulators datastore start --no-legacy --host-port 0.0.0.0:8380
    ports:
      - 8380:8380

  pubsub:
    image: google/cloud-sdk
    environment:
      - CLOUDSDK_CORE_PROJECT=compositor
    command: gcloud beta emulators pubsub start --host-port 0.0.0.0:8538
    ports:
      - 8538:8538
