version: '2'
volumes:
  qubit-api-postgres:
    external: true
services:
  test:
    build: ./tests/integration
    environment:
      - API_WEB_SERVICE_ADDRESS=web.api.qubit.site:9000
      - GOOGLE_PROJECT_ID=qubit-161916
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
    working_dir: /workspace/tests/integration
    volumes:
      - .:/workspace
      - /workspace/tests/integration/node_modules
    networks:
      - default
    depends_on:
      - api-web
      - compute-web
