version: '2'
volumes:
  qubit-api-postgres:
    external: true
  qubit-compute-postgres:
    external: true
services:
  api-web:
    image: us.gcr.io/qubit-161916/api-web
    build: ./applications/api/services/web
    environment:
      - API_SERVICE_ADDRESS=web.api.qubit.site:9000
      - APP_ENV=development
      - COMPUTE_SERVICE_ADDRESS=web.compute.qubit.site:9000
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - POSTGRES_URL=postgres://postgres@postgres.api.qubit.site:5432/postgres?sslmode=disable
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      default:
        aliases:
          - web.api.qubit.site
    depends_on:
      - api-postgres
      - compute-web
  api-postgres:
    image: postgres:9.6
    volumes:
      - qubit-api-postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres.api.qubit.site

  compute-web:
    image: us.gcr.io/qubit-161916/compute-web
    build: ./applications/compute/services/web
    environment:
      - APP_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - POSTGRES_URL=postgres://postgres@postgres.compute.qubit.site:5432/postgres?sslmode=disable
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      default:
        aliases:
          - web.compute.qubit.site
    depends_on:
      - compute-postgres
  compute-coordinator:
    image: us.gcr.io/qubit-161916/compute-coordinator
    build: ./applications/compute/services/coordinator
    environment:
      - APP_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - POSTGRES_URL=postgres://postgres@postgres.compute.qubit.site:5432/postgres?sslmode=disable
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      - default
    depends_on:
      - compute-postgres
      - compute-processor
  compute-processor:
    image: us.gcr.io/qubit-161916/compute-processor
    build: ./applications/compute/services/processor
    environment:
      - APP_ENV=development
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - GOOGLE_PROJECT_ID=qubit-161916
      - PORT=9000
      - STORAGE_BUCKET=qubit-dev-161916
    volumes:
      - ./credentials:/opt/etc/credentials
    networks:
      default:
        aliases:
          - processor.compute.qubit.site
  compute-postgres:
    image: postgres:9.6
    volumes:
      - qubit-compute-postgres:/var/lib/postgresql/data
    networks:
      default:
        aliases:
          - postgres.compute.qubit.site
