version: '2'
services:
  api:
    image: us.gcr.io/qubit-161916/api
    build: ./services/api
    environment:
      - GOOGLE_PROJECT_ID=qubit-161916
      - DATASTORE_PROJECT_ID=qubit-161916
      - DATASTORE_DATASET=qubit
      - DATASTORE_EMULATOR_HOST=datastore:8380
      - DATASTORE_HOST=datastore:8380
      - STORAGE_BUCKET=qubit-dev-161916
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - PORT=9000
      - API_SERVICE_ADDRESS=api:9000
      - COMPUTE_SERVICE_ADDRESS=compute:9000
    volumes:
      - ./credentials:/opt/etc/credentials
    depends_on:
      - datastore
      - compute

  compute:
    image: us.gcr.io/qubit-161916/compute
    build: ./services/compute
    environment:
      - GOOGLE_PROJECT_ID=qubit-161916
      - DATASTORE_PROJECT_ID=qubit-161916
      - DATASTORE_DATASET=qubit
      - DATASTORE_EMULATOR_HOST=datastore:8380
      - DATASTORE_HOST=datastore:8380
      - STORAGE_BUCKET=qubit-dev-161916
      - GOOGLE_APPLICATION_CREDENTIALS=/opt/etc/credentials/service-account-key-file.json
      - PORT=9000
    volumes:
      - ./credentials:/opt/etc/credentials

  datastore:
    image: google/cloud-sdk
    environment:
      - CLOUDSDK_CORE_PROJECT=compositor
    command: gcloud beta emulators datastore start --no-legacy --host-port 0.0.0.0:8380
    ports:
      - 8380:8380
