// Code generated by protoc-gen-go. DO NOT EDIT.
// source: parameters/parameters.proto

/*
Package parameters is a generated protocol buffer package.

It is generated from these files:
	parameters/parameters.proto

It has these top-level messages:
	Parameter
	ListParametersRequest
	ListParametersResponse
	GetParameterRequest
	CreateParameterRequest
	UpdateParameterRequest
	DeleteParameterRequest
	RenderParameterRequest
	RenderParameterResponse
*/
package parameters

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import geometry "github.com/stupschwartz/qubit/proto-gen/go/geometry"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Parameter struct {
	Id         string            `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	OperatorId string            `protobuf:"bytes,2,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
	Type       string            `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	Data       []byte            `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	Labels     map[string]string `protobuf:"bytes,5,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Parameter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Parameter) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

func (m *Parameter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Parameter) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *Parameter) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type ListParametersRequest struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListParametersRequest) Reset()                    { *m = ListParametersRequest{} }
func (m *ListParametersRequest) String() string            { return proto.CompactTextString(m) }
func (*ListParametersRequest) ProtoMessage()               {}
func (*ListParametersRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListParametersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListParametersRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListParametersResponse struct {
	Parameters    []*Parameter `protobuf:"bytes,1,rep,name=parameters" json:"parameters,omitempty"`
	NextPageToken string       `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListParametersResponse) Reset()                    { *m = ListParametersResponse{} }
func (m *ListParametersResponse) String() string            { return proto.CompactTextString(m) }
func (*ListParametersResponse) ProtoMessage()               {}
func (*ListParametersResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListParametersResponse) GetParameters() []*Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *ListParametersResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetParameterRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetParameterRequest) Reset()                    { *m = GetParameterRequest{} }
func (m *GetParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*GetParameterRequest) ProtoMessage()               {}
func (*GetParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateParameterRequest struct {
	Parameter *Parameter `protobuf:"bytes,1,opt,name=parameter" json:"parameter,omitempty"`
}

func (m *CreateParameterRequest) Reset()                    { *m = CreateParameterRequest{} }
func (m *CreateParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateParameterRequest) ProtoMessage()               {}
func (*CreateParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateParameterRequest) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type UpdateParameterRequest struct {
	Id        string     `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Parameter *Parameter `protobuf:"bytes,2,opt,name=parameter" json:"parameter,omitempty"`
}

func (m *UpdateParameterRequest) Reset()                    { *m = UpdateParameterRequest{} }
func (m *UpdateParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateParameterRequest) ProtoMessage()               {}
func (*UpdateParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateParameterRequest) GetParameter() *Parameter {
	if m != nil {
		return m.Parameter
	}
	return nil
}

type DeleteParameterRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteParameterRequest) Reset()                    { *m = DeleteParameterRequest{} }
func (m *DeleteParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteParameterRequest) ProtoMessage()               {}
func (*DeleteParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RenderParameterRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	// TODO: use double?
	Frame       int32                   `protobuf:"varint,2,opt,name=frame" json:"frame,omitempty"`
	BoundingBox *geometry.BoundingBox2D `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
}

func (m *RenderParameterRequest) Reset()                    { *m = RenderParameterRequest{} }
func (m *RenderParameterRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderParameterRequest) ProtoMessage()               {}
func (*RenderParameterRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *RenderParameterRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RenderParameterRequest) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *RenderParameterRequest) GetBoundingBox() *geometry.BoundingBox2D {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

type RenderParameterResponse struct {
	ResultUrl  string `protobuf:"bytes,1,opt,name=result_url,json=resultUrl" json:"result_url,omitempty"`
	ResultType string `protobuf:"bytes,2,opt,name=result_type,json=resultType" json:"result_type,omitempty"`
}

func (m *RenderParameterResponse) Reset()                    { *m = RenderParameterResponse{} }
func (m *RenderParameterResponse) String() string            { return proto.CompactTextString(m) }
func (*RenderParameterResponse) ProtoMessage()               {}
func (*RenderParameterResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *RenderParameterResponse) GetResultUrl() string {
	if m != nil {
		return m.ResultUrl
	}
	return ""
}

func (m *RenderParameterResponse) GetResultType() string {
	if m != nil {
		return m.ResultType
	}
	return ""
}

func init() {
	proto.RegisterType((*Parameter)(nil), "parameters.Parameter")
	proto.RegisterType((*ListParametersRequest)(nil), "parameters.ListParametersRequest")
	proto.RegisterType((*ListParametersResponse)(nil), "parameters.ListParametersResponse")
	proto.RegisterType((*GetParameterRequest)(nil), "parameters.GetParameterRequest")
	proto.RegisterType((*CreateParameterRequest)(nil), "parameters.CreateParameterRequest")
	proto.RegisterType((*UpdateParameterRequest)(nil), "parameters.UpdateParameterRequest")
	proto.RegisterType((*DeleteParameterRequest)(nil), "parameters.DeleteParameterRequest")
	proto.RegisterType((*RenderParameterRequest)(nil), "parameters.RenderParameterRequest")
	proto.RegisterType((*RenderParameterResponse)(nil), "parameters.RenderParameterResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Parameters service

type ParametersClient interface {
	List(ctx context.Context, in *ListParametersRequest, opts ...grpc.CallOption) (*ListParametersResponse, error)
	Get(ctx context.Context, in *GetParameterRequest, opts ...grpc.CallOption) (*Parameter, error)
	Create(ctx context.Context, in *CreateParameterRequest, opts ...grpc.CallOption) (*Parameter, error)
	Update(ctx context.Context, in *UpdateParameterRequest, opts ...grpc.CallOption) (*Parameter, error)
	Delete(ctx context.Context, in *DeleteParameterRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Render(ctx context.Context, in *RenderParameterRequest, opts ...grpc.CallOption) (*RenderParameterResponse, error)
}

type parametersClient struct {
	cc *grpc.ClientConn
}

func NewParametersClient(cc *grpc.ClientConn) ParametersClient {
	return &parametersClient{cc}
}

func (c *parametersClient) List(ctx context.Context, in *ListParametersRequest, opts ...grpc.CallOption) (*ListParametersResponse, error) {
	out := new(ListParametersResponse)
	err := grpc.Invoke(ctx, "/parameters.Parameters/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parametersClient) Get(ctx context.Context, in *GetParameterRequest, opts ...grpc.CallOption) (*Parameter, error) {
	out := new(Parameter)
	err := grpc.Invoke(ctx, "/parameters.Parameters/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parametersClient) Create(ctx context.Context, in *CreateParameterRequest, opts ...grpc.CallOption) (*Parameter, error) {
	out := new(Parameter)
	err := grpc.Invoke(ctx, "/parameters.Parameters/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parametersClient) Update(ctx context.Context, in *UpdateParameterRequest, opts ...grpc.CallOption) (*Parameter, error) {
	out := new(Parameter)
	err := grpc.Invoke(ctx, "/parameters.Parameters/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parametersClient) Delete(ctx context.Context, in *DeleteParameterRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/parameters.Parameters/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *parametersClient) Render(ctx context.Context, in *RenderParameterRequest, opts ...grpc.CallOption) (*RenderParameterResponse, error) {
	out := new(RenderParameterResponse)
	err := grpc.Invoke(ctx, "/parameters.Parameters/Render", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Parameters service

type ParametersServer interface {
	List(context.Context, *ListParametersRequest) (*ListParametersResponse, error)
	Get(context.Context, *GetParameterRequest) (*Parameter, error)
	Create(context.Context, *CreateParameterRequest) (*Parameter, error)
	Update(context.Context, *UpdateParameterRequest) (*Parameter, error)
	Delete(context.Context, *DeleteParameterRequest) (*google_protobuf1.Empty, error)
	Render(context.Context, *RenderParameterRequest) (*RenderParameterResponse, error)
}

func RegisterParametersServer(s *grpc.Server, srv ParametersServer) {
	s.RegisterService(&_Parameters_serviceDesc, srv)
}

func _Parameters_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListParametersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).List(ctx, req.(*ListParametersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parameters_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).Get(ctx, req.(*GetParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parameters_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).Create(ctx, req.(*CreateParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parameters_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).Update(ctx, req.(*UpdateParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parameters_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).Delete(ctx, req.(*DeleteParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Parameters_Render_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderParameterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ParametersServer).Render(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/parameters.Parameters/Render",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ParametersServer).Render(ctx, req.(*RenderParameterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Parameters_serviceDesc = grpc.ServiceDesc{
	ServiceName: "parameters.Parameters",
	HandlerType: (*ParametersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Parameters_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Parameters_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Parameters_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Parameters_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Parameters_Delete_Handler,
		},
		{
			MethodName: "Render",
			Handler:    _Parameters_Render_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "parameters/parameters.proto",
}

func init() { proto.RegisterFile("parameters/parameters.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 653 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x54, 0xdf, 0x4f, 0xd4, 0x40,
	0x10, 0xce, 0xfd, 0x8c, 0x37, 0x87, 0x48, 0x16, 0x29, 0x97, 0x1e, 0x06, 0x58, 0x23, 0x21, 0x3e,
	0xb4, 0xf1, 0x88, 0x89, 0xf0, 0x88, 0x10, 0x63, 0x82, 0x09, 0x29, 0xf0, 0xa0, 0x89, 0xb9, 0xec,
	0xa5, 0xc3, 0xa5, 0xa1, 0x74, 0x6b, 0xbb, 0x45, 0x0e, 0xe3, 0x8b, 0xff, 0x82, 0x7f, 0x9a, 0x6f,
	0x3e, 0xfb, 0x77, 0x18, 0xdb, 0xed, 0xde, 0xb5, 0x3d, 0x16, 0xf0, 0x6d, 0xf6, 0x9b, 0xe9, 0xf7,
	0xcd, 0x74, 0xbe, 0x5d, 0xe8, 0x87, 0x2c, 0x62, 0x97, 0x28, 0x30, 0x8a, 0xed, 0x22, 0xb4, 0xc2,
	0x88, 0x0b, 0x4e, 0xa0, 0x40, 0xcc, 0xb5, 0x31, 0xe7, 0x63, 0x1f, 0x6d, 0x16, 0x7a, 0x36, 0x0b,
	0x02, 0x2e, 0x98, 0xf0, 0x78, 0xa0, 0x2a, 0xcd, 0xbe, 0xca, 0xca, 0xd3, 0x28, 0x39, 0xb7, 0xf1,
	0x32, 0x14, 0x13, 0x95, 0x5c, 0x1d, 0x23, 0x4f, 0x59, 0xa2, 0x89, 0x3d, 0x0d, 0xf2, 0x04, 0xfd,
	0x5d, 0x83, 0xce, 0xf1, 0x54, 0x82, 0x2c, 0x42, 0xdd, 0x73, 0x7b, 0xb5, 0x8d, 0xda, 0x76, 0xc7,
	0x49, 0x23, 0xb2, 0x0e, 0x5d, 0x1e, 0x62, 0xc4, 0x04, 0x8f, 0x86, 0x69, 0xa2, 0x2e, 0x13, 0x30,
	0x85, 0xde, 0xbb, 0x84, 0x40, 0x53, 0x4c, 0x42, 0xec, 0x35, 0x64, 0x46, 0xc6, 0x19, 0xe6, 0x32,
	0xc1, 0x7a, 0xcd, 0x14, 0x5b, 0x70, 0x64, 0x4c, 0x76, 0xa1, 0xed, 0xb3, 0x11, 0xfa, 0x71, 0xaf,
	0xb5, 0xd1, 0xd8, 0xee, 0x0e, 0x36, 0xad, 0xd2, 0xa4, 0x33, 0x7d, 0xeb, 0x48, 0xd6, 0x1c, 0x06,
	0x69, 0x7f, 0x8e, 0xfa, 0xc0, 0xdc, 0x85, 0x6e, 0x09, 0x26, 0x4b, 0xd0, 0xb8, 0xc0, 0x89, 0xea,
	0x31, 0x0b, 0xc9, 0x53, 0x68, 0x5d, 0x31, 0x3f, 0x41, 0xd5, 0x5e, 0x7e, 0xd8, 0xab, 0xbf, 0xa9,
	0xd1, 0x13, 0x58, 0x39, 0xf2, 0x62, 0x31, 0xe3, 0x8f, 0x1d, 0xfc, 0x92, 0x60, 0x2c, 0x48, 0x1f,
	0x3a, 0x21, 0x1b, 0xe3, 0x30, 0xf6, 0x6e, 0x50, 0x52, 0xb5, 0x9c, 0x47, 0x19, 0x70, 0x92, 0x9e,
	0xc9, 0x33, 0x00, 0x99, 0x14, 0xfc, 0x02, 0x03, 0x45, 0x2a, 0xcb, 0x4f, 0x33, 0x80, 0x7e, 0x05,
	0x63, 0x9e, 0x34, 0x0e, 0xd3, 0x35, 0x20, 0x79, 0x0d, 0xa5, 0x6d, 0xa5, 0xb4, 0xd9, 0xa0, 0x2b,
	0xda, 0x41, 0x9d, 0x52, 0x21, 0xd9, 0x82, 0x27, 0x01, 0x5e, 0x8b, 0xe1, 0x2d, 0xd1, 0xc7, 0x19,
	0x7c, 0x3c, 0x13, 0x7e, 0x01, 0xcb, 0xef, 0xb0, 0xd0, 0x9d, 0xce, 0x32, 0xb7, 0x33, 0xfa, 0x01,
	0x8c, 0xb7, 0x11, 0x32, 0x81, 0xb7, 0x2a, 0x77, 0xb2, 0xa9, 0x15, 0x26, 0x3f, 0xb8, 0xb3, 0xbd,
	0xa2, 0x8e, 0x7e, 0x06, 0xe3, 0x2c, 0x74, 0x75, 0x74, 0xf3, 0x66, 0xa9, 0xd0, 0xd7, 0xff, 0x93,
	0x7e, 0x1b, 0x8c, 0x03, 0xf4, 0xf1, 0x61, 0x7a, 0x7a, 0x03, 0x86, 0x83, 0x81, 0x8b, 0xd1, 0x83,
	0x8d, 0xa4, 0x86, 0x38, 0xcf, 0x4a, 0x64, 0x13, 0x2d, 0x27, 0x3f, 0x90, 0x3d, 0x58, 0x18, 0xf1,
	0x24, 0x70, 0xbd, 0x60, 0x3c, 0x1c, 0xf1, 0x6b, 0x69, 0xd9, 0xee, 0x60, 0xd5, 0x9a, 0x5d, 0x88,
	0x7d, 0x95, 0xdd, 0xe7, 0xd7, 0x83, 0x03, 0xa7, 0x3b, 0x2a, 0x8e, 0xf4, 0x23, 0xac, 0xde, 0xd2,
	0x56, 0x4b, 0x4f, 0xdd, 0x12, 0x61, 0x9c, 0xf8, 0x62, 0x98, 0x44, 0xbe, 0x6a, 0xa2, 0x93, 0x23,
	0x67, 0x91, 0x9f, 0xdd, 0x20, 0x95, 0x96, 0xf7, 0x44, 0xdd, 0xa0, 0x1c, 0x3a, 0x4d, 0x91, 0xc1,
	0xdf, 0x26, 0x40, 0xe1, 0x25, 0x82, 0xd0, 0xcc, 0xdc, 0x45, 0x2a, 0x17, 0x44, 0x6b, 0x62, 0x93,
	0xde, 0x57, 0x92, 0x77, 0x47, 0x8d, 0x1f, 0xbf, 0xfe, 0xfc, 0xac, 0x2f, 0x91, 0x45, 0xfb, 0xea,
	0x55, 0xe9, 0x71, 0x21, 0x9f, 0xa0, 0x91, 0x7a, 0x89, 0xac, 0x97, 0x29, 0x34, 0xe6, 0x32, 0xf5,
	0x0b, 0xa4, 0x7d, 0x49, 0xbb, 0x42, 0x96, 0xab, 0xb4, 0xf6, 0x37, 0xcf, 0xfd, 0x4e, 0xce, 0xa1,
	0x9d, 0x1b, 0x90, 0x54, 0x3a, 0xd4, 0x9b, 0xf2, 0x2e, 0x85, 0x4d, 0xa9, 0xd0, 0xa7, 0x73, 0x8d,
	0xef, 0x15, 0xd6, 0x21, 0x17, 0xd0, 0xce, 0x9d, 0x59, 0xd5, 0xd1, 0xbb, 0xf5, 0x2e, 0x9d, 0x2d,
	0xa9, 0xb3, 0x61, 0xea, 0x26, 0x29, 0x8b, 0x31, 0x68, 0xe7, 0x3e, 0xad, 0x8a, 0xe9, 0xbd, 0x6b,
	0x1a, 0x56, 0xfe, 0x18, 0x5b, 0xd3, 0xc7, 0xd8, 0x3a, 0xcc, 0x1e, 0xe3, 0xe9, 0x7f, 0x7b, 0xa9,
	0xfd, 0x6f, 0x09, 0xb4, 0x73, 0x93, 0x55, 0x25, 0xf4, 0xa6, 0x37, 0x9f, 0xdf, 0x5b, 0xa3, 0xd6,
	0x4f, 0xa5, 0xde, 0x1a, 0x35, 0x35, 0x7a, 0x76, 0x24, 0x3f, 0x1a, 0xb5, 0x65, 0x8f, 0x3b, 0xff,
	0x02, 0x00, 0x00, 0xff, 0xff, 0x38, 0xe8, 0x9c, 0x23, 0x87, 0x06, 0x00, 0x00,
}
