version: 2
jobs:
    build:
        docker:
            - image: docker:17

        working_directory: /workspace

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Pull
                command: |
                    docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
                    docker pull ${DOCKER_USER}/qubit-builder || echo "Getting qubit-builder"

            - run:
                name: Build
                command: |
                    docker build -t ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1} -t ${DOCKER_USER}/qubit-builder:latest ./builder/

            - run:
                name: Push
                command: |
                    docker push ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1}
                    docker push ${DOCKER_USER}/qubit-builder:latest

            - run:
                name: Trigger Containers Build
                command: |
                    docker run --rm ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1} curl -u ${CIRCLE_API_TOKEN}: --data build_parameters[CIRCLE_JOB]=build_containers --data revision=${CIRCLE_SHA1} https://circleci.com/api/v1.1/project/github/stupschwartz/qubit/tree/${CIRCLE_BRANCH}

    build_containers:
        docker:
            - image: stuschwartz/qubit-builder:latest

        working_directory: /go/src/github.com/stupschwartz/qubit

        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Authenticate GCloud
                command: scripts/auth-gcloud.sh

            - run:
                name: Build Compute Container
                command: |
                    gcloud docker -- build -t ${EXTERNALREGISTRYENDPOINT}/qubit-compute:${CIRCLE_SHA1} ./compute/
                    gcloud docker -- push ${EXTERNALREGISTRYENDPOINT}/qubit-compute:${CIRCLE_SHA1}

            - run:
                name: Build Server Container
                command: |
                    gcloud docker -- build -t ${EXTERNALREGISTRYENDPOINT}/qubit-server:${CIRCLE_SHA1} ./server/
                    gcloud docker -- push ${EXTERNALREGISTRYENDPOINT}/qubit-server:${CIRCLE_SHA1}

            - run:
                name: Trigger Containers Deployment
                command: |
                    curl -u ${CIRCLE_API_TOKEN}: --data build_parameters[CIRCLE_JOB]=deploy_containers --data revision=${CIRCLE_SHA1} https://circleci.com/api/v1.1/project/github/stupschwartz/qubit/tree/${CIRCLE_BRANCH}


    deploy_containers:
        docker:
            - image: stuschwartz/qubit-builder:latest

        working_directory: /go/src/github.com/stupschwartz/qubit

        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Authenticate GCloud
                command: scripts/auth-gcloud.sh

            - run:
                name: Cluster Credentials
                command: |
                    gcloud container clusters get-credentials dev-cluster --zone us-central1-a

            - run:
                name: Deploy API Services
                command: scripts/deploy.sh
