version: 2
jobs:
    build:
        docker:
            - image: docker:17

        working_directory: /workspace

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Pull
                command: |
                    docker login -e ${DOCKER_EMAIL} -u ${DOCKER_USER} -p ${DOCKER_PASS}
                    docker pull ${DOCKER_USER}/qubit-builder || echo "Getting qubit-builder"

            - run:
                name: Build
                command: |
                    docker build --no-cache -t ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1} -t ${DOCKER_USER}/qubit-builder:latest ./builder/

            - run:
                name: Push
                command: |
                    docker push ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1}
                    docker push ${DOCKER_USER}/qubit-builder:latest

            - run:
                name: Trigger Containers Build
                command: |
                    docker run --rm ${DOCKER_USER}/qubit-builder:${CIRCLE_SHA1} curl -u ${CIRCLE_API_TOKEN}: --data build_parameters[CIRCLE_JOB]=build_containers --data revision=${CIRCLE_SHA1} https://circleci.com/api/v1.1/project/github/stupschwartz/qubit/tree/${CIRCLE_BRANCH}

    build_containers:
        docker:
            - image: stuschwartz/qubit-builder:latest

        working_directory: /go/src/github.com/stupschwartz/qubit

        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Authenticate GCloud
                command: scripts/auth-gcloud.sh

            # BUILD COMPUTE
            - run:
                name: Compute - Start Go Build
                command: |
                    docker create -v /go -w /go/src/github.com/stupschwartz/qubit/compute --name go-compute-build-volumes alpine:3.4 /bin/true

            - run:
                name: Compute - Copy Source to Container
                command: |
                    docker cp ./ go-compute-build-volumes:/go/src/github.com/stupschwartz/qubit

            - run:
                name: Compute - Build Go Code
                command: |
                    docker run --volumes-from go-compute-build-volumes -w /go/src/github.com/stupschwartz/qubit/compute golang:1.8 bash -c "go get .; go build"

            - run:
                name: Compute - Copy Back Artifacts
                command: |
                    docker cp go-compute-build-volumes:/go/src/github.com/stupschwartz/qubit/compute/compute `pwd`/compute/compute

            - run:
                name: Compute - Build Container
                command: |
                    gcloud docker -- build -t ${EXTERNALREGISTRYENDPOINT}/qubit-compute:${CIRCLE_SHA1} ./compute/

            - run:
                name: Compute - Push Container
                command: |
                    gcloud docker -- push ${EXTERNALREGISTRYENDPOINT}/qubit-compute:${CIRCLE_SHA1}

            # BUILD SERVER
            - run:
                name: Server - Start Go Build
                command: |
                    docker create -v /go -w /go/src/github.com/stupschwartz/qubit/server --name go-server-build-volumes alpine:3.4 /bin/true

            - run:
                name: Server - Copy Source to Container
                command: |
                    docker cp ./ go-server-build-volumes:/go/src/github.com/stupschwartz/qubit

            - run:
                name: Server - Build Go Code
                command: |
                    docker run --volumes-from go-server-build-volumes -w /go/src/github.com/stupschwartz/qubit/server golang:1.8 bash -c "go get .; go build"

            - run:
                name: Server - Copy Back Artifacts
                command: |
                    docker cp go-server-build-volumes:/go/src/github.com/stupschwartz/qubit/server/server `pwd`/server/server

            - run:
                name: Server - Build Container
                command: |
                    gcloud docker -- build -t ${EXTERNALREGISTRYENDPOINT}/qubit-server:${CIRCLE_SHA1} ./server/

            - run:
                name: Server - Push Container
                command: |
                    gcloud docker -- push ${EXTERNALREGISTRYENDPOINT}/qubit-server:${CIRCLE_SHA1}

            # TRIGGER NEXT STEP
            - run:
                name: Trigger Containers Deployment
                command: |
                    curl -u ${CIRCLE_API_TOKEN}: --data build_parameters[CIRCLE_JOB]=deploy_containers --data revision=${CIRCLE_SHA1} https://circleci.com/api/v1.1/project/github/stupschwartz/qubit/tree/${CIRCLE_BRANCH}


    deploy_containers:
        docker:
            - image: stuschwartz/qubit-builder:latest

        working_directory: /go/src/github.com/stupschwartz/qubit

        environment:
            TEST_RESULTS: /tmp/test-results

        steps:
            - checkout
            - setup_remote_docker

            - run:
                name: Authenticate GCloud
                command: scripts/auth-gcloud.sh

            - run:
                name: Cluster Credentials
                command: |
                    gcloud container clusters get-credentials dev-cluster --zone us-central1-a

            - run:
                name: Deploy API Services
                command: ./deploy.sh
