// Code generated by protoc-gen-go.
// source: operators.proto
// DO NOT EDIT!

/*
Package operators is a generated protocol buffer package.

It is generated from these files:
	operators.proto

It has these top-level messages:
	Operator
	ListOperatorsRequest
	ListOperatorsResponse
	GetOperatorRequest
	CreateOperatorRequest
	UpdateOperatorRequest
	DeleteOperatorRequest
*/
package operators

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Operator struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *Operator) Reset()                    { *m = Operator{} }
func (m *Operator) String() string            { return proto.CompactTextString(m) }
func (*Operator) ProtoMessage()               {}
func (*Operator) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Operator) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ListOperatorsRequest struct {
	OrganizationId int64  `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	SceneId        int64  `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	PageSize       int32  `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken      string `protobuf:"bytes,4,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListOperatorsRequest) Reset()                    { *m = ListOperatorsRequest{} }
func (m *ListOperatorsRequest) String() string            { return proto.CompactTextString(m) }
func (*ListOperatorsRequest) ProtoMessage()               {}
func (*ListOperatorsRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListOperatorsRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *ListOperatorsRequest) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *ListOperatorsRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListOperatorsRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListOperatorsResponse struct {
	Operators     []*Operator `protobuf:"bytes,1,rep,name=operators" json:"operators,omitempty"`
	NextPageToken string      `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListOperatorsResponse) Reset()                    { *m = ListOperatorsResponse{} }
func (m *ListOperatorsResponse) String() string            { return proto.CompactTextString(m) }
func (*ListOperatorsResponse) ProtoMessage()               {}
func (*ListOperatorsResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListOperatorsResponse) GetOperators() []*Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

func (m *ListOperatorsResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetOperatorRequest struct {
	OrganizationId int64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	SceneId        int64 `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	OperatorId     int64 `protobuf:"varint,3,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
}

func (m *GetOperatorRequest) Reset()                    { *m = GetOperatorRequest{} }
func (m *GetOperatorRequest) String() string            { return proto.CompactTextString(m) }
func (*GetOperatorRequest) ProtoMessage()               {}
func (*GetOperatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetOperatorRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *GetOperatorRequest) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *GetOperatorRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

type CreateOperatorRequest struct {
	OrganizationId int64     `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	SceneId        int64     `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	Operator       *Operator `protobuf:"bytes,3,opt,name=operator" json:"operator,omitempty"`
}

func (m *CreateOperatorRequest) Reset()                    { *m = CreateOperatorRequest{} }
func (m *CreateOperatorRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateOperatorRequest) ProtoMessage()               {}
func (*CreateOperatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateOperatorRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *CreateOperatorRequest) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *CreateOperatorRequest) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

type UpdateOperatorRequest struct {
	OrganizationId int64     `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	SceneId        int64     `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	OperatorId     int64     `protobuf:"varint,3,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
	Operator       *Operator `protobuf:"bytes,4,opt,name=operator" json:"operator,omitempty"`
}

func (m *UpdateOperatorRequest) Reset()                    { *m = UpdateOperatorRequest{} }
func (m *UpdateOperatorRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateOperatorRequest) ProtoMessage()               {}
func (*UpdateOperatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UpdateOperatorRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *UpdateOperatorRequest) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *UpdateOperatorRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func (m *UpdateOperatorRequest) GetOperator() *Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

type DeleteOperatorRequest struct {
	OrganizationId int64 `protobuf:"varint,1,opt,name=organization_id,json=organizationId" json:"organization_id,omitempty"`
	SceneId        int64 `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	OperatorId     int64 `protobuf:"varint,3,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
}

func (m *DeleteOperatorRequest) Reset()                    { *m = DeleteOperatorRequest{} }
func (m *DeleteOperatorRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteOperatorRequest) ProtoMessage()               {}
func (*DeleteOperatorRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *DeleteOperatorRequest) GetOrganizationId() int64 {
	if m != nil {
		return m.OrganizationId
	}
	return 0
}

func (m *DeleteOperatorRequest) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *DeleteOperatorRequest) GetOperatorId() int64 {
	if m != nil {
		return m.OperatorId
	}
	return 0
}

func init() {
	proto.RegisterType((*Operator)(nil), "operators.Operator")
	proto.RegisterType((*ListOperatorsRequest)(nil), "operators.ListOperatorsRequest")
	proto.RegisterType((*ListOperatorsResponse)(nil), "operators.ListOperatorsResponse")
	proto.RegisterType((*GetOperatorRequest)(nil), "operators.GetOperatorRequest")
	proto.RegisterType((*CreateOperatorRequest)(nil), "operators.CreateOperatorRequest")
	proto.RegisterType((*UpdateOperatorRequest)(nil), "operators.UpdateOperatorRequest")
	proto.RegisterType((*DeleteOperatorRequest)(nil), "operators.DeleteOperatorRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Operators service

type OperatorsClient interface {
	List(ctx context.Context, in *ListOperatorsRequest, opts ...grpc.CallOption) (*ListOperatorsResponse, error)
	Get(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	Create(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	Update(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*Operator, error)
	Delete(ctx context.Context, in *DeleteOperatorRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type operatorsClient struct {
	cc *grpc.ClientConn
}

func NewOperatorsClient(cc *grpc.ClientConn) OperatorsClient {
	return &operatorsClient{cc}
}

func (c *operatorsClient) List(ctx context.Context, in *ListOperatorsRequest, opts ...grpc.CallOption) (*ListOperatorsResponse, error) {
	out := new(ListOperatorsResponse)
	err := grpc.Invoke(ctx, "/operators.Operators/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorsClient) Get(ctx context.Context, in *GetOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	out := new(Operator)
	err := grpc.Invoke(ctx, "/operators.Operators/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorsClient) Create(ctx context.Context, in *CreateOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	out := new(Operator)
	err := grpc.Invoke(ctx, "/operators.Operators/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorsClient) Update(ctx context.Context, in *UpdateOperatorRequest, opts ...grpc.CallOption) (*Operator, error) {
	out := new(Operator)
	err := grpc.Invoke(ctx, "/operators.Operators/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *operatorsClient) Delete(ctx context.Context, in *DeleteOperatorRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/operators.Operators/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Operators service

type OperatorsServer interface {
	List(context.Context, *ListOperatorsRequest) (*ListOperatorsResponse, error)
	Get(context.Context, *GetOperatorRequest) (*Operator, error)
	Create(context.Context, *CreateOperatorRequest) (*Operator, error)
	Update(context.Context, *UpdateOperatorRequest) (*Operator, error)
	Delete(context.Context, *DeleteOperatorRequest) (*google_protobuf1.Empty, error)
}

func RegisterOperatorsServer(s *grpc.Server, srv OperatorsServer) {
	s.RegisterService(&_Operators_serviceDesc, srv)
}

func _Operators_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListOperatorsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operators.Operators/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorsServer).List(ctx, req.(*ListOperatorsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operators_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorsServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operators.Operators/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorsServer).Get(ctx, req.(*GetOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operators_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operators.Operators/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorsServer).Create(ctx, req.(*CreateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operators_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operators.Operators/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorsServer).Update(ctx, req.(*UpdateOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Operators_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteOperatorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OperatorsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/operators.Operators/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OperatorsServer).Delete(ctx, req.(*DeleteOperatorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Operators_serviceDesc = grpc.ServiceDesc{
	ServiceName: "operators.Operators",
	HandlerType: (*OperatorsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Operators_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Operators_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Operators_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Operators_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Operators_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "operators.proto",
}

func init() { proto.RegisterFile("operators.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 519 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xc4, 0x95, 0x41, 0x6b, 0xd4, 0x40,
	0x14, 0xc7, 0xc9, 0x66, 0x5d, 0x77, 0x5f, 0xb1, 0x85, 0xd1, 0x95, 0x35, 0xb5, 0xb4, 0xcc, 0x41,
	0x8b, 0x87, 0x0c, 0xad, 0x37, 0x2f, 0x22, 0x2a, 0xa5, 0xa8, 0x54, 0xa3, 0x3d, 0x78, 0x0a, 0xa9,
	0x79, 0x86, 0x60, 0xcd, 0xc4, 0xcc, 0x54, 0x6c, 0x75, 0x2f, 0x5e, 0xbc, 0x78, 0x10, 0x05, 0xc1,
	0x9b, 0x5f, 0xc0, 0x4f, 0xe3, 0x57, 0xf0, 0x83, 0x38, 0x33, 0xd9, 0x49, 0xb2, 0x35, 0x45, 0xa1,
	0xbb, 0x78, 0xdb, 0x79, 0xef, 0xcd, 0xfe, 0x7f, 0xf3, 0xcf, 0x7f, 0x18, 0x58, 0xe2, 0x39, 0x16,
	0x91, 0xe4, 0x85, 0xf0, 0xf3, 0x82, 0x4b, 0x4e, 0x06, 0x55, 0xc1, 0xbb, 0x9c, 0x70, 0x9e, 0xec,
	0x23, 0x8b, 0xf2, 0x94, 0x45, 0x59, 0xc6, 0x65, 0x24, 0x53, 0x9e, 0x4d, 0x06, 0xbd, 0xe5, 0x49,
	0xd7, 0xac, 0xf6, 0x0e, 0x9e, 0x33, 0x7c, 0x99, 0xcb, 0xc3, 0xb2, 0x49, 0x3d, 0xe8, 0xef, 0x4c,
	0xfe, 0x87, 0x2c, 0x42, 0x27, 0x8d, 0x47, 0xce, 0x9a, 0xb3, 0xee, 0x06, 0xea, 0x17, 0xfd, 0xea,
	0xc0, 0x85, 0xfb, 0xa9, 0x90, 0x76, 0x40, 0x04, 0xf8, 0xea, 0x00, 0x85, 0x24, 0x57, 0x15, 0x4d,
	0x91, 0x44, 0x59, 0x7a, 0x64, 0x84, 0xc2, 0x6a, 0xd7, 0x62, 0xb3, 0xbc, 0x1d, 0x93, 0x4b, 0xd0,
	0x17, 0xcf, 0x30, 0x43, 0x3d, 0xd1, 0x31, 0x13, 0x67, 0xcd, 0x5a, 0xb5, 0x96, 0x61, 0x90, 0x47,
	0x09, 0x86, 0x22, 0x3d, 0xc2, 0x91, 0xab, 0x7a, 0x67, 0x82, 0xbe, 0x2e, 0x3c, 0x56, 0x6b, 0xb2,
	0x02, 0x60, 0x9a, 0x92, 0xbf, 0xc0, 0x6c, 0xd4, 0x55, 0xdd, 0x41, 0x60, 0xc6, 0x9f, 0xe8, 0x02,
	0x2d, 0x60, 0x78, 0x8c, 0x4b, 0xe4, 0xea, 0xbc, 0x48, 0x36, 0xa0, 0x76, 0x45, 0x21, 0xb9, 0xeb,
	0x0b, 0x9b, 0xe7, 0xfd, 0xda, 0x38, 0xbb, 0x21, 0xa8, 0xa7, 0xc8, 0x15, 0x58, 0xca, 0xf0, 0x8d,
	0x0c, 0x1b, 0x7a, 0x1d, 0xa3, 0x77, 0x4e, 0x97, 0x1f, 0x56, 0x9a, 0x87, 0x40, 0xb6, 0xb0, 0x92,
	0x9c, 0xa5, 0x13, 0xab, 0xb0, 0x60, 0x71, 0x74, 0xd7, 0x35, 0x5d, 0xb0, 0xa5, 0xed, 0x98, 0x7e,
	0x74, 0x60, 0x78, 0xbb, 0xc0, 0x48, 0xe2, 0x3c, 0xe4, 0x19, 0xf4, 0xad, 0x96, 0xd1, 0x3e, 0xc1,
	0xb2, 0x6a, 0x88, 0xfe, 0x50, 0x38, 0xbb, 0x79, 0x3c, 0x27, 0x9c, 0xbf, 0xb9, 0x31, 0xc5, 0xdb,
	0xfd, 0x17, 0xde, 0x77, 0x30, 0xbc, 0x83, 0xfb, 0xf8, 0x7f, 0x70, 0x37, 0x3f, 0xf4, 0x60, 0x50,
	0x05, 0x95, 0x7c, 0x76, 0xa0, 0xab, 0xa3, 0x4b, 0x56, 0x1b, 0xcc, 0x6d, 0x77, 0xcc, 0x5b, 0x3b,
	0x79, 0xa0, 0x0c, 0x3b, 0xdd, 0x7a, 0xff, 0xf3, 0xd7, 0x97, 0xce, 0x2d, 0x72, 0x93, 0xbd, 0xde,
	0x60, 0x4d, 0x62, 0xc1, 0xde, 0x1e, 0x3b, 0xd7, 0x98, 0x19, 0x5e, 0xd5, 0xb0, 0xe7, 0x18, 0xb3,
	0xfa, 0x0a, 0x7c, 0x72, 0xc0, 0x55, 0xd9, 0x26, 0x2b, 0x0d, 0xc9, 0x3f, 0xb3, 0xee, 0xb5, 0xd9,
	0x4c, 0x77, 0x0d, 0xc4, 0x0e, 0x79, 0x70, 0x4a, 0x08, 0x35, 0x5d, 0xdb, 0x38, 0xd6, 0x3e, 0xf5,
	0xca, 0xc8, 0x93, 0xa6, 0x11, 0xad, 0xb7, 0xa0, 0x1d, 0xec, 0x91, 0x01, 0xbb, 0x47, 0x4f, 0xeb,
	0xce, 0x8d, 0x2a, 0x48, 0xe4, 0xbb, 0x82, 0x2a, 0x83, 0x3f, 0x05, 0xd5, 0x7a, 0x17, 0xda, 0xa1,
	0x42, 0x03, 0xf5, 0xd4, 0x9b, 0xad, 0x5b, 0x0d, 0xc4, 0x6f, 0x0a, 0xb1, 0x0c, 0xfb, 0x14, 0x62,
	0x6b, 0xfe, 0xbd, 0x8b, 0x7e, 0xf9, 0x32, 0xf8, 0xf6, 0x65, 0xf0, 0xef, 0xea, 0x97, 0xc1, 0x7e,
	0xd3, 0x6b, 0xb3, 0xa5, 0xdc, 0xeb, 0x19, 0x99, 0xeb, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0x5e,
	0x80, 0xea, 0x7d, 0xca, 0x06, 0x00, 0x00,
}
