# Default values for qubit-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: nginx
  tag: stable
  pullPolicy: IfNotPresent
service:
  name: nginx
  type: ClusterIP
  externalPort: 80
  internalPort: 80
ingress:
  enabled: false
  # Used to create Ingress record (should used with service.type: ClusterIP).
  hosts:
    - chart-example.local
  annotations:
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  tls:
    # Secrets must be manually created in the namespace.
    # - secretName: chart-example-tls
    #   hosts:
    #     - chart-example.local
resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

# My Configuration

GoogleProjectId: qubit-161916
Githash:
DatastoreDataset: qubit


Api:
    ApiName: api.endpoints.qubit-161916.cloud.goog
    ApiId:
    AppName: api
    ImageName: us.gcr.io/qubit-161916/api
    StorageBucket: qubit-dev-161916
    InternalPort: 9000
    ExternalHttpPort: 9005
    ExternalHttp2Port: 9010
    Replicas: 1
    MaxSurge: 2


# Copied out of incubator/cassandra
Cassandra:
    Name: cassandra

    ## Cassandra image version
    ## ref: https://hub.docker.com/r/library/cassandra/
    Image:
      Repo: "cassandra"
      Tag: "3"
      PullPolicy: IfNotPresent

    ## Specify a service type
    ## ref: http://kubernetes.io/docs/user-guide/services/
    Service:
      Type: ClusterIP

    ## Persist data to a persitent volume
    Persistence:
      Enabled: true
      ## If defined, volume.beta.kubernetes.io/storage-class: <storageClass>
      ## Default: volume.alpha.kubernetes.io/storage-class: default
      StorageClass: generic
      AccessMode: ReadWriteOnce
      Size: 10Gi

    ## Configure resource requests and limits
    ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
    ## Minimum memory for development is 4GB and 2 CPU cores
    ## Minimum memory for production is 8GB and 4 CPU cores
    ## ref: http://docs.datastax.com/en/archived/cassandra/2.0/cassandra/architecture/architecturePlanningHardware_c.html
    Resources:
      Requests:
        Memory: 4Gi
        CPU: 2
      Limits:
        Memory: 4Gi
        CPU: 2

    ## Change cassandra configuration paramaters below:
    ## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/configuration/configCassandra_yaml.html
    ## Recommended max heap size is 1/2 of system memory
    ## Recommeneed heap new size is 1/4 of max heap size
    ## ref: http://docs.datastax.com/en/cassandra/3.0/cassandra/operations/opsTuneJVM.html
    Config:
      ClusterName: cassandra
      ClusterSize: 3
      SeedSize: 2
      NumTokens: 256
      DcName: DC1
      RackName: RAC1
      EndpointSnitch: SimpleSnitch
      MaxHeapSize: 2048M
      HeapNewSize: 512M
      Ports:
        Cql: 9042
        Thrift: 9160

    ## Configure node selector. Edit code below for adding selector to pods
    ## ref: https://kubernetes.io/docs/user-guide/node-selection/
    # selector:
      # nodeSelector:
        # cloud.google.com/gke-nodepool: pool-db