apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: compute-deployment
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: compute
    spec:
      containers:
      - name: compute
        image: gcr.io/qubit-161916/qubit-compute:latest
        ports:
        - containerPort: 10000
        env:
        - name: DATASTORE_PROJECT_ID
          value: qubit-161916
        - name: DATASTORE_DATASET
          value: qubit
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /opt/etc/credentials/service-account-key-file.json
        volumeMounts:
        - name: google-credentials
          mountPath: /opt/etc/credentials
      volumes:
      - name: google-credentials
        secret:
          secretName: google-service-account
