// Code generated by protoc-gen-go.
// source: compute.proto
// DO NOT EDIT!

/*
Package protos is a generated protocol buffer package.

It is generated from these files:
	compute.proto

It has these top-level messages:
	RenderRequest
	RenderResponse
	ImageFrame
	ImagePlane
	ImageComponent
	Row
	Node
	Component
	Parameter
	BoundingBox
	Scene
*/
package protos

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RenderRequest struct {
	SceneId     string       `protobuf:"bytes,1,opt,name=sceneId" json:"sceneId,omitempty"`
	NodeId      string       `protobuf:"bytes,2,opt,name=nodeId" json:"nodeId,omitempty"`
	BoundingBox *BoundingBox `protobuf:"bytes,3,opt,name=boundingBox" json:"boundingBox,omitempty"`
}

func (m *RenderRequest) Reset()                    { *m = RenderRequest{} }
func (m *RenderRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()               {}
func (*RenderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RenderRequest) GetSceneId() string {
	if m != nil {
		return m.SceneId
	}
	return ""
}

func (m *RenderRequest) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *RenderRequest) GetBoundingBox() *BoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

type RenderResponse struct {
	ImagePlane  *ImagePlane  `protobuf:"bytes,1,opt,name=imagePlane" json:"imagePlane,omitempty"`
	BoundingBox *BoundingBox `protobuf:"bytes,2,opt,name=boundingBox" json:"boundingBox,omitempty"`
}

func (m *RenderResponse) Reset()                    { *m = RenderResponse{} }
func (m *RenderResponse) String() string            { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()               {}
func (*RenderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RenderResponse) GetImagePlane() *ImagePlane {
	if m != nil {
		return m.ImagePlane
	}
	return nil
}

func (m *RenderResponse) GetBoundingBox() *BoundingBox {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

type ImageFrame struct {
	Labels      []string      `protobuf:"bytes,1,rep,name=labels" json:"labels,omitempty"`
	ImagePlanes []*ImagePlane `protobuf:"bytes,2,rep,name=imagePlanes" json:"imagePlanes,omitempty"`
}

func (m *ImageFrame) Reset()                    { *m = ImageFrame{} }
func (m *ImageFrame) String() string            { return proto.CompactTextString(m) }
func (*ImageFrame) ProtoMessage()               {}
func (*ImageFrame) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ImageFrame) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ImageFrame) GetImagePlanes() []*ImagePlane {
	if m != nil {
		return m.ImagePlanes
	}
	return nil
}

type ImagePlane struct {
	Width      int64             `protobuf:"varint,1,opt,name=width" json:"width,omitempty"`
	Height     int64             `protobuf:"varint,2,opt,name=height" json:"height,omitempty"`
	Labels     []string          `protobuf:"bytes,3,rep,name=labels" json:"labels,omitempty"`
	Components []*ImageComponent `protobuf:"bytes,4,rep,name=components" json:"components,omitempty"`
}

func (m *ImagePlane) Reset()                    { *m = ImagePlane{} }
func (m *ImagePlane) String() string            { return proto.CompactTextString(m) }
func (*ImagePlane) ProtoMessage()               {}
func (*ImagePlane) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ImagePlane) GetWidth() int64 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *ImagePlane) GetHeight() int64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *ImagePlane) GetLabels() []string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *ImagePlane) GetComponents() []*ImageComponent {
	if m != nil {
		return m.Components
	}
	return nil
}

type ImageComponent struct {
	Rows []*Row `protobuf:"bytes,1,rep,name=rows" json:"rows,omitempty"`
}

func (m *ImageComponent) Reset()                    { *m = ImageComponent{} }
func (m *ImageComponent) String() string            { return proto.CompactTextString(m) }
func (*ImageComponent) ProtoMessage()               {}
func (*ImageComponent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ImageComponent) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Row struct {
	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data" json:"data,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Row) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

type Node struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Node) Reset()                    { *m = Node{} }
func (m *Node) String() string            { return proto.CompactTextString(m) }
func (*Node) ProtoMessage()               {}
func (*Node) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Node) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type Component struct {
	Label string  `protobuf:"bytes,1,opt,name=label" json:"label,omitempty"`
	Value float64 `protobuf:"fixed64,2,opt,name=value" json:"value,omitempty"`
}

func (m *Component) Reset()                    { *m = Component{} }
func (m *Component) String() string            { return proto.CompactTextString(m) }
func (*Component) ProtoMessage()               {}
func (*Component) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Component) GetLabel() string {
	if m != nil {
		return m.Label
	}
	return ""
}

func (m *Component) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

type Parameter struct {
	Name       string       `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Components []*Component `protobuf:"bytes,2,rep,name=components" json:"components,omitempty"`
}

func (m *Parameter) Reset()                    { *m = Parameter{} }
func (m *Parameter) String() string            { return proto.CompactTextString(m) }
func (*Parameter) ProtoMessage()               {}
func (*Parameter) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *Parameter) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Parameter) GetComponents() []*Component {
	if m != nil {
		return m.Components
	}
	return nil
}

// BoundingBox
type BoundingBox struct {
	StartX int64 `protobuf:"varint,1,opt,name=start_x,json=startX" json:"start_x,omitempty"`
	StartY int64 `protobuf:"varint,2,opt,name=start_y,json=startY" json:"start_y,omitempty"`
	EndX   int64 `protobuf:"varint,3,opt,name=end_x,json=endX" json:"end_x,omitempty"`
	EndY   int64 `protobuf:"varint,4,opt,name=end_y,json=endY" json:"end_y,omitempty"`
}

func (m *BoundingBox) Reset()                    { *m = BoundingBox{} }
func (m *BoundingBox) String() string            { return proto.CompactTextString(m) }
func (*BoundingBox) ProtoMessage()               {}
func (*BoundingBox) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *BoundingBox) GetStartX() int64 {
	if m != nil {
		return m.StartX
	}
	return 0
}

func (m *BoundingBox) GetStartY() int64 {
	if m != nil {
		return m.StartY
	}
	return 0
}

func (m *BoundingBox) GetEndX() int64 {
	if m != nil {
		return m.EndX
	}
	return 0
}

func (m *BoundingBox) GetEndY() int64 {
	if m != nil {
		return m.EndY
	}
	return 0
}

// Scene
type Scene struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Scene) Reset()                    { *m = Scene{} }
func (m *Scene) String() string            { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()               {}
func (*Scene) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *Scene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func init() {
	proto.RegisterType((*RenderRequest)(nil), "protos.RenderRequest")
	proto.RegisterType((*RenderResponse)(nil), "protos.RenderResponse")
	proto.RegisterType((*ImageFrame)(nil), "protos.ImageFrame")
	proto.RegisterType((*ImagePlane)(nil), "protos.ImagePlane")
	proto.RegisterType((*ImageComponent)(nil), "protos.ImageComponent")
	proto.RegisterType((*Row)(nil), "protos.Row")
	proto.RegisterType((*Node)(nil), "protos.Node")
	proto.RegisterType((*Component)(nil), "protos.Component")
	proto.RegisterType((*Parameter)(nil), "protos.Parameter")
	proto.RegisterType((*BoundingBox)(nil), "protos.BoundingBox")
	proto.RegisterType((*Scene)(nil), "protos.Scene")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compute service

type ComputeClient interface {
	Render(ctx context.Context, opts ...grpc.CallOption) (Compute_RenderClient, error)
}

type computeClient struct {
	cc *grpc.ClientConn
}

func NewComputeClient(cc *grpc.ClientConn) ComputeClient {
	return &computeClient{cc}
}

func (c *computeClient) Render(ctx context.Context, opts ...grpc.CallOption) (Compute_RenderClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_Compute_serviceDesc.Streams[0], c.cc, "/protos.Compute/Render", opts...)
	if err != nil {
		return nil, err
	}
	x := &computeRenderClient{stream}
	return x, nil
}

type Compute_RenderClient interface {
	Send(*RenderRequest) error
	Recv() (*RenderResponse, error)
	grpc.ClientStream
}

type computeRenderClient struct {
	grpc.ClientStream
}

func (x *computeRenderClient) Send(m *RenderRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *computeRenderClient) Recv() (*RenderResponse, error) {
	m := new(RenderResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for Compute service

type ComputeServer interface {
	Render(Compute_RenderServer) error
}

func RegisterComputeServer(s *grpc.Server, srv ComputeServer) {
	s.RegisterService(&_Compute_serviceDesc, srv)
}

func _Compute_Render_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ComputeServer).Render(&computeRenderServer{stream})
}

type Compute_RenderServer interface {
	Send(*RenderResponse) error
	Recv() (*RenderRequest, error)
	grpc.ServerStream
}

type computeRenderServer struct {
	grpc.ServerStream
}

func (x *computeRenderServer) Send(m *RenderResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *computeRenderServer) Recv() (*RenderRequest, error) {
	m := new(RenderRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _Compute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "protos.Compute",
	HandlerType: (*ComputeServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Render",
			Handler:       _Compute_Render_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "compute.proto",
}

func init() { proto.RegisterFile("compute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 471 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x8c, 0x53, 0xcf, 0x6b, 0xdb, 0x30,
	0x14, 0x9e, 0x6c, 0x27, 0x21, 0xcf, 0x34, 0x6c, 0x6a, 0xe7, 0x9a, 0xc1, 0x58, 0xd0, 0x29, 0xa7,
	0xb2, 0x7a, 0xbf, 0x4e, 0xbb, 0xa4, 0x30, 0xd6, 0xcb, 0x28, 0xda, 0xa5, 0xdd, 0xa5, 0x28, 0xd5,
	0x23, 0x31, 0x24, 0x52, 0x66, 0x29, 0x4b, 0xca, 0xfe, 0x83, 0xfd, 0xd5, 0xc3, 0x92, 0x95, 0xd8,
	0x61, 0x83, 0x9e, 0x92, 0x4f, 0xdf, 0xf3, 0xfb, 0xbe, 0x4f, 0x4f, 0x0f, 0x4e, 0x1e, 0xf4, 0x6a,
	0xbd, 0xb1, 0x78, 0xb1, 0xae, 0xb4, 0xd5, 0xb4, 0xef, 0x7e, 0x0c, 0xdb, 0xc1, 0x09, 0x47, 0x25,
	0xb1, 0xe2, 0xf8, 0x73, 0x83, 0xc6, 0xd2, 0x1c, 0x06, 0xe6, 0x01, 0x15, 0x5e, 0xcb, 0x9c, 0x8c,
	0xc9, 0x64, 0xc8, 0x03, 0xa4, 0x19, 0xf4, 0x95, 0x96, 0x35, 0x11, 0x39, 0xa2, 0x41, 0xf4, 0x03,
	0xa4, 0x33, 0xbd, 0x51, 0xb2, 0x54, 0xf3, 0xa9, 0xde, 0xe5, 0xf1, 0x98, 0x4c, 0xd2, 0xe2, 0xd4,
	0xeb, 0x98, 0x8b, 0xe9, 0x81, 0xe2, 0xed, 0x3a, 0xf6, 0x1b, 0x46, 0x41, 0xd9, 0xac, 0xb5, 0x32,
	0x48, 0x0b, 0x80, 0x72, 0x25, 0xe6, 0x78, 0xb3, 0x14, 0x0a, 0x9d, 0x7a, 0x5a, 0xd0, 0xd0, 0xe7,
	0x7a, 0xcf, 0xf0, 0x56, 0xd5, 0xb1, 0x78, 0xf4, 0x44, 0xf1, 0x1f, 0x00, 0xae, 0xe1, 0x97, 0x4a,
	0xac, 0xb0, 0x4e, 0xb6, 0x14, 0x33, 0x5c, 0x9a, 0x9c, 0x8c, 0xe3, 0x3a, 0x99, 0x47, 0xf4, 0x3d,
	0xa4, 0x07, 0x29, 0x93, 0x47, 0xe3, 0xf8, 0x3f, 0x8e, 0xda, 0x65, 0xec, 0x0f, 0x69, 0x9a, 0x7b,
	0x87, 0x67, 0xd0, 0xdb, 0x96, 0xd2, 0x2e, 0x5c, 0xa0, 0x98, 0x7b, 0x50, 0x4b, 0x2e, 0xb0, 0x9c,
	0x2f, 0xac, 0xb3, 0x1c, 0xf3, 0x06, 0xb5, 0xac, 0xc4, 0x1d, 0x2b, 0x1f, 0x01, 0xea, 0x01, 0x6a,
	0x85, 0xca, 0x9a, 0x3c, 0x71, 0x4e, 0xb2, 0x8e, 0x93, 0xab, 0x40, 0xf3, 0x56, 0x25, 0xbb, 0x84,
	0x51, 0x97, 0xa5, 0x6f, 0x20, 0xa9, 0xf4, 0xd6, 0x47, 0x4d, 0x8b, 0x34, 0xf4, 0xe0, 0x7a, 0xcb,
	0x1d, 0xc1, 0x5e, 0x43, 0xcc, 0xf5, 0x96, 0x66, 0x90, 0x48, 0x61, 0x85, 0xab, 0x23, 0xd3, 0xe8,
	0x39, 0xe1, 0x0e, 0xb3, 0x0c, 0x92, 0x6f, 0x5a, 0x22, 0x1d, 0x41, 0x54, 0x86, 0x37, 0x12, 0x95,
	0x92, 0x7d, 0x82, 0xe1, 0x41, 0xe4, 0x0c, 0x7a, 0xce, 0x78, 0xc3, 0x7b, 0x50, 0x9f, 0xfe, 0x12,
	0xcb, 0x0d, 0xba, 0xcc, 0x84, 0x7b, 0xc0, 0x38, 0x0c, 0x6f, 0x44, 0x3d, 0x07, 0x8b, 0x15, 0xa5,
	0x90, 0x28, 0xb1, 0xc2, 0xe6, 0x3b, 0xf7, 0x9f, 0x5e, 0x76, 0xb2, 0xfb, 0x29, 0xbc, 0x08, 0xbe,
	0xff, 0x1d, 0xbb, 0x84, 0xb4, 0x35, 0x7b, 0x7a, 0x0e, 0x03, 0x63, 0x45, 0x65, 0xef, 0x77, 0xcd,
	0x14, 0xfa, 0x0e, 0xde, 0x1e, 0x88, 0xc7, 0x30, 0x07, 0x07, 0xef, 0xe8, 0x29, 0xf4, 0x50, 0xc9,
	0x7b, 0xff, 0x9c, 0x63, 0x9e, 0xa0, 0x92, 0xb7, 0xe1, 0xf0, 0x31, 0x4f, 0xf6, 0x87, 0x77, 0xec,
	0x1c, 0x7a, 0xdf, 0xeb, 0x0d, 0x39, 0xbe, 0x90, 0xe2, 0x2b, 0x0c, 0xae, 0xfc, 0xce, 0xd1, 0xcf,
	0xd0, 0xf7, 0x6f, 0x9d, 0xbe, 0xdc, 0xdf, 0x77, 0x7b, 0xeb, 0x5e, 0x65, 0xc7, 0xc7, 0x7e, 0x25,
	0xd8, 0xb3, 0x09, 0x79, 0x4b, 0x66, 0x7e, 0x59, 0xdf, 0xfd, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xcf,
	0x49, 0xf4, 0xb1, 0xc4, 0x03, 0x00, 0x00,
}
