// Code generated by protoc-gen-go. DO NOT EDIT.
// source: renders/renders.proto

/*
Package renders is a generated protocol buffer package.

It is generated from these files:
	renders/renders.proto

It has these top-level messages:
	RenderRequest
	RenderResponse
*/
package renders

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RenderRequest struct {
	OperatorId string `protobuf:"bytes,1,opt,name=operator_id,json=operatorId" json:"operator_id,omitempty"`
}

func (m *RenderRequest) Reset()                    { *m = RenderRequest{} }
func (m *RenderRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderRequest) ProtoMessage()               {}
func (*RenderRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RenderRequest) GetOperatorId() string {
	if m != nil {
		return m.OperatorId
	}
	return ""
}

type RenderResponse struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *RenderResponse) Reset()                    { *m = RenderResponse{} }
func (m *RenderResponse) String() string            { return proto.CompactTextString(m) }
func (*RenderResponse) ProtoMessage()               {}
func (*RenderResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RenderResponse) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*RenderRequest)(nil), "renders.RenderRequest")
	proto.RegisterType((*RenderResponse)(nil), "renders.RenderResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Renders service

type RendersClient interface {
	DoRender(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error)
}

type rendersClient struct {
	cc *grpc.ClientConn
}

func NewRendersClient(cc *grpc.ClientConn) RendersClient {
	return &rendersClient{cc}
}

func (c *rendersClient) DoRender(ctx context.Context, in *RenderRequest, opts ...grpc.CallOption) (*RenderResponse, error) {
	out := new(RenderResponse)
	err := grpc.Invoke(ctx, "/renders.Renders/DoRender", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Renders service

type RendersServer interface {
	DoRender(context.Context, *RenderRequest) (*RenderResponse, error)
}

func RegisterRendersServer(s *grpc.Server, srv RendersServer) {
	s.RegisterService(&_Renders_serviceDesc, srv)
}

func _Renders_DoRender_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RendersServer).DoRender(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/renders.Renders/DoRender",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RendersServer).DoRender(ctx, req.(*RenderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Renders_serviceDesc = grpc.ServiceDesc{
	ServiceName: "renders.Renders",
	HandlerType: (*RendersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DoRender",
			Handler:    _Renders_DoRender_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "renders/renders.proto",
}

func init() { proto.RegisterFile("renders/renders.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 147 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x4a, 0xcd, 0x4b,
	0x49, 0x2d, 0x2a, 0xd6, 0x87, 0xd2, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0xec, 0x50, 0xae,
	0x92, 0x01, 0x17, 0x6f, 0x10, 0x98, 0x19, 0x94, 0x5a, 0x58, 0x9a, 0x5a, 0x5c, 0x22, 0x24, 0xcf,
	0xc5, 0x9d, 0x5f, 0x90, 0x5a, 0x94, 0x58, 0x92, 0x5f, 0x14, 0x9f, 0x99, 0x22, 0xc1, 0xa8, 0xc0,
	0xa8, 0xc1, 0x19, 0xc4, 0x05, 0x13, 0xf2, 0x4c, 0x51, 0x52, 0xe1, 0xe2, 0x83, 0xe9, 0x28, 0x2e,
	0xc8, 0xcf, 0x2b, 0x4e, 0x15, 0x12, 0xe2, 0x62, 0x49, 0x49, 0x2c, 0x49, 0x04, 0xab, 0xe5, 0x09,
	0x02, 0xb3, 0x8d, 0x3c, 0xb8, 0xd8, 0x21, 0xaa, 0x8a, 0x85, 0x6c, 0xb9, 0x38, 0x5c, 0xf2, 0x21,
	0x1c, 0x21, 0x31, 0x3d, 0x98, 0x3b, 0x50, 0x6c, 0x95, 0x12, 0xc7, 0x10, 0x87, 0x98, 0xad, 0xc4,
	0x90, 0xc4, 0x06, 0x76, 0xb1, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x98, 0x6a, 0x5a, 0xdb, 0xca,
	0x00, 0x00, 0x00,
}
