apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: http-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api
        backend:
          serviceName: {{ .Values.Api.AppName }}
          servicePort: {{ .Values.Api.ExternalHttpPort }}
