apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{ .Values.Compute.AppName }}
spec:
  replicas: {{ .Values.Compute.Replicas }}
  template:
    metadata:
      labels:
        app: {{ .Values.Compute.AppName }}
    spec:
      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:1
        args: [
          "-P", "{{ .Values.Compute.ExternalPort }}",
          "-s", "{{ .Values.Compute.ApiName }}",
          "-v", "{{ .Values.Compute.ApiId }}",
          "-a", "grpc://127.0.0.1:{{ .Values.Compute.InternalPort }}"
        ]
        ports:
          - containerPort: {{ .Values.Compute.ExternalPort }}
      - name: compute
        image: us.gcr.io/qubit-161916/qubit-compute:{{ .Values.Githash }}
        ports:
          - containerPort: {{ .Values.Compute.InternalPort }}
        env:
          - name: GOOGLE_PROJECT_ID
            value: {{ .Values.GoogleProjectId }}
          - name: DATASTORE_PROJECT_ID
            value: {{ .Values.GoogleProjectId }}
          - name: DATASTORE_DATASET
            value: {{ .Values.DatastoreDataset }}
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /opt/etc/credentials/service-account-key-file.json
          - name: STORAGE_BUCKET
            value: {{ .Values.Compute.StorageBucket }}
        volumeMounts:
          - name: google-credentials
            mountPath: /opt/etc/credentials
      volumes:
        - name: google-credentials
          secret:
            secretName: google-service-account
