apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: primary-ingress
spec:
  rules:
  - http:
      paths:
      - path: /api/v1
        backend:
          serviceName: api
          servicePort: {{ .Values.Api.ExternalHttp2Port }}
