// Code generated by protoc-gen-go. DO NOT EDIT.
// source: images/images.proto

/*
Package images is a generated protocol buffer package.

It is generated from these files:
	images/images.proto

It has these top-level messages:
	Image
	Plane
	Channel
	Row
	ListImagesRequest
	ListImagesResponse
	GetImageRequest
	CreateImageRequest
	UpdateImageRequest
	DeleteImageRequest
*/
package images

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Image struct {
	Id      int64             `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	SceneId int64             `protobuf:"varint,2,opt,name=scene_id,json=sceneId" json:"scene_id,omitempty"`
	Name    string            `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Width   int32             `protobuf:"varint,4,opt,name=width" json:"width,omitempty"`
	Height  int32             `protobuf:"varint,5,opt,name=height" json:"height,omitempty"`
	Labels  map[string]string `protobuf:"bytes,6,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Planes  []*Plane          `protobuf:"bytes,7,rep,name=planes" json:"planes,omitempty"`
}

func (m *Image) Reset()                    { *m = Image{} }
func (m *Image) String() string            { return proto.CompactTextString(m) }
func (*Image) ProtoMessage()               {}
func (*Image) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Image) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Image) GetSceneId() int64 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *Image) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Image) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Image) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Image) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Image) GetPlanes() []*Plane {
	if m != nil {
		return m.Planes
	}
	return nil
}

type Plane struct {
	Name     string            `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Width    int32             `protobuf:"varint,2,opt,name=width" json:"width,omitempty"`
	Height   int32             `protobuf:"varint,3,opt,name=height" json:"height,omitempty"`
	Labels   map[string]string `protobuf:"bytes,4,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Channels []*Channel        `protobuf:"bytes,5,rep,name=channels" json:"channels,omitempty"`
}

func (m *Plane) Reset()                    { *m = Plane{} }
func (m *Plane) String() string            { return proto.CompactTextString(m) }
func (*Plane) ProtoMessage()               {}
func (*Plane) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Plane) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Plane) GetWidth() int32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *Plane) GetHeight() int32 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Plane) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

func (m *Plane) GetChannels() []*Channel {
	if m != nil {
		return m.Channels
	}
	return nil
}

type Channel struct {
	Name string `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Rows []*Row `protobuf:"bytes,2,rep,name=rows" json:"rows,omitempty"`
}

func (m *Channel) Reset()                    { *m = Channel{} }
func (m *Channel) String() string            { return proto.CompactTextString(m) }
func (*Channel) ProtoMessage()               {}
func (*Channel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Channel) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Channel) GetRows() []*Row {
	if m != nil {
		return m.Rows
	}
	return nil
}

type Row struct {
	Data []float64 `protobuf:"fixed64,1,rep,packed,name=data" json:"data,omitempty"`
}

func (m *Row) Reset()                    { *m = Row{} }
func (m *Row) String() string            { return proto.CompactTextString(m) }
func (*Row) ProtoMessage()               {}
func (*Row) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Row) GetData() []float64 {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListImagesRequest struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListImagesRequest) Reset()                    { *m = ListImagesRequest{} }
func (m *ListImagesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListImagesRequest) ProtoMessage()               {}
func (*ListImagesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ListImagesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListImagesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListImagesResponse struct {
	Images        []*Image `protobuf:"bytes,1,rep,name=images" json:"images,omitempty"`
	NextPageToken string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListImagesResponse) Reset()                    { *m = ListImagesResponse{} }
func (m *ListImagesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListImagesResponse) ProtoMessage()               {}
func (*ListImagesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListImagesResponse) GetImages() []*Image {
	if m != nil {
		return m.Images
	}
	return nil
}

func (m *ListImagesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetImageRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetImageRequest) Reset()                    { *m = GetImageRequest{} }
func (m *GetImageRequest) String() string            { return proto.CompactTextString(m) }
func (*GetImageRequest) ProtoMessage()               {}
func (*GetImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *GetImageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type CreateImageRequest struct {
	Image *Image `protobuf:"bytes,1,opt,name=image" json:"image,omitempty"`
}

func (m *CreateImageRequest) Reset()                    { *m = CreateImageRequest{} }
func (m *CreateImageRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateImageRequest) ProtoMessage()               {}
func (*CreateImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *CreateImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type UpdateImageRequest struct {
	Id    int64  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Image *Image `protobuf:"bytes,2,opt,name=image" json:"image,omitempty"`
}

func (m *UpdateImageRequest) Reset()                    { *m = UpdateImageRequest{} }
func (m *UpdateImageRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateImageRequest) ProtoMessage()               {}
func (*UpdateImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UpdateImageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UpdateImageRequest) GetImage() *Image {
	if m != nil {
		return m.Image
	}
	return nil
}

type DeleteImageRequest struct {
	Id int64 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteImageRequest) Reset()                    { *m = DeleteImageRequest{} }
func (m *DeleteImageRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteImageRequest) ProtoMessage()               {}
func (*DeleteImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *DeleteImageRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func init() {
	proto.RegisterType((*Image)(nil), "images.Image")
	proto.RegisterType((*Plane)(nil), "images.Plane")
	proto.RegisterType((*Channel)(nil), "images.Channel")
	proto.RegisterType((*Row)(nil), "images.Row")
	proto.RegisterType((*ListImagesRequest)(nil), "images.ListImagesRequest")
	proto.RegisterType((*ListImagesResponse)(nil), "images.ListImagesResponse")
	proto.RegisterType((*GetImageRequest)(nil), "images.GetImageRequest")
	proto.RegisterType((*CreateImageRequest)(nil), "images.CreateImageRequest")
	proto.RegisterType((*UpdateImageRequest)(nil), "images.UpdateImageRequest")
	proto.RegisterType((*DeleteImageRequest)(nil), "images.DeleteImageRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Images service

type ImagesClient interface {
	List(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error)
	Get(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error)
	Create(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*Image, error)
	Update(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*Image, error)
	Delete(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
}

type imagesClient struct {
	cc *grpc.ClientConn
}

func NewImagesClient(cc *grpc.ClientConn) ImagesClient {
	return &imagesClient{cc}
}

func (c *imagesClient) List(ctx context.Context, in *ListImagesRequest, opts ...grpc.CallOption) (*ListImagesResponse, error) {
	out := new(ListImagesResponse)
	err := grpc.Invoke(ctx, "/images.Images/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) Get(ctx context.Context, in *GetImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/images.Images/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) Create(ctx context.Context, in *CreateImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/images.Images/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) Update(ctx context.Context, in *UpdateImageRequest, opts ...grpc.CallOption) (*Image, error) {
	out := new(Image)
	err := grpc.Invoke(ctx, "/images.Images/Update", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *imagesClient) Delete(ctx context.Context, in *DeleteImageRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/images.Images/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Images service

type ImagesServer interface {
	List(context.Context, *ListImagesRequest) (*ListImagesResponse, error)
	Get(context.Context, *GetImageRequest) (*Image, error)
	Create(context.Context, *CreateImageRequest) (*Image, error)
	Update(context.Context, *UpdateImageRequest) (*Image, error)
	Delete(context.Context, *DeleteImageRequest) (*google_protobuf1.Empty, error)
}

func RegisterImagesServer(s *grpc.Server, srv ImagesServer) {
	s.RegisterService(&_Images_serviceDesc, srv)
}

func _Images_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListImagesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.Images/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).List(ctx, req.(*ListImagesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.Images/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).Get(ctx, req.(*GetImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.Images/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).Create(ctx, req.(*CreateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.Images/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).Update(ctx, req.(*UpdateImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Images_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ImagesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/images.Images/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ImagesServer).Delete(ctx, req.(*DeleteImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Images_serviceDesc = grpc.ServiceDesc{
	ServiceName: "images.Images",
	HandlerType: (*ImagesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Images_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Images_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Images_Create_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Images_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Images_Delete_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "images/images.proto",
}

func init() { proto.RegisterFile("images/images.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 646 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xa4, 0x54, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0x4f, 0xdb, 0x6d, 0x61, 0x1f, 0x22, 0xf8, 0x50, 0x58, 0x8a, 0x28, 0x56, 0x34, 0x44, 0x93,
	0x6d, 0xc0, 0x8b, 0x70, 0xf0, 0x20, 0x12, 0x43, 0x42, 0x14, 0x47, 0x3d, 0x18, 0x0f, 0xa4, 0xb0,
	0xe3, 0x6e, 0x43, 0x69, 0xeb, 0x76, 0x00, 0xd1, 0x78, 0xf1, 0xe6, 0xd9, 0x4f, 0xe2, 0x67, 0xf1,
	0x2b, 0xf0, 0x41, 0x9c, 0x79, 0xd3, 0x96, 0xa5, 0xad, 0x5c, 0x3c, 0x6d, 0xdf, 0xbf, 0xdf, 0xfb,
	0xfd, 0x7e, 0x33, 0x3b, 0x30, 0x13, 0x1e, 0x05, 0x7d, 0x9e, 0xf9, 0xfa, 0xa7, 0x9b, 0x0e, 0x13,
	0x91, 0xa0, 0xa3, 0x23, 0xf7, 0x76, 0x3f, 0x49, 0xfa, 0x11, 0xf7, 0x83, 0x34, 0xf4, 0x83, 0x38,
	0x4e, 0x44, 0x20, 0xc2, 0x24, 0xce, 0xbb, 0xdc, 0x85, 0xbc, 0x4a, 0xd1, 0xfe, 0xf1, 0x27, 0x9f,
	0x1f, 0xa5, 0xe2, 0x4c, 0x17, 0xbd, 0x9f, 0x26, 0xd8, 0xdb, 0x0a, 0x05, 0xaf, 0x83, 0x19, 0xf6,
	0x3a, 0xc6, 0x92, 0xb1, 0x62, 0x31, 0xf9, 0x85, 0xf3, 0x30, 0x9e, 0x1d, 0xf0, 0x98, 0xef, 0xc9,
	0xac, 0x49, 0xd9, 0x31, 0x8a, 0xb7, 0x7b, 0x88, 0xd0, 0x8a, 0x83, 0x23, 0xde, 0xb1, 0x64, 0xba,
	0xcd, 0xe8, 0x1b, 0x6f, 0x82, 0x7d, 0x1a, 0xf6, 0xc4, 0xa0, 0xd3, 0x92, 0x49, 0x9b, 0xe9, 0x00,
	0x67, 0xc1, 0x19, 0xf0, 0xb0, 0x3f, 0x10, 0x1d, 0x9b, 0xd2, 0x79, 0x84, 0xab, 0xe0, 0x44, 0xc1,
	0x3e, 0x8f, 0xb2, 0x8e, 0xb3, 0x64, 0xad, 0x4c, 0xac, 0xcd, 0x77, 0x73, 0x61, 0xc4, 0xa5, 0xbb,
	0x43, 0xb5, 0xad, 0x58, 0x0c, 0xcf, 0x58, 0xde, 0x88, 0x0f, 0xc0, 0x49, 0xa3, 0x20, 0xe6, 0x59,
	0x67, 0x8c, 0x46, 0x26, 0x8b, 0x91, 0x5d, 0x95, 0x65, 0x79, 0xd1, 0x5d, 0x87, 0x89, 0x91, 0x69,
	0x9c, 0x06, 0xeb, 0x90, 0x9f, 0x91, 0xac, 0x36, 0x53, 0x9f, 0x8a, 0xe8, 0x49, 0x10, 0x1d, 0x73,
	0x12, 0xd5, 0x66, 0x3a, 0xd8, 0x30, 0x9f, 0x1a, 0xde, 0xb9, 0x01, 0x36, 0x81, 0x95, 0x02, 0x8d,
	0x26, 0x81, 0x66, 0xb3, 0x40, 0xeb, 0x1f, 0x02, 0x5b, 0x97, 0x05, 0xd2, 0x82, 0x46, 0x81, 0x8f,
	0x61, 0xfc, 0x60, 0x20, 0x8f, 0x4f, 0x0d, 0xd9, 0x34, 0x34, 0x55, 0x0c, 0x6d, 0xea, 0x3c, 0x2b,
	0x1b, 0xfe, 0x47, 0xe6, 0x33, 0x18, 0xcb, 0xf1, 0x1a, 0x75, 0xde, 0x85, 0xd6, 0x30, 0x39, 0xcd,
	0xe4, 0x9c, 0xa2, 0x30, 0x51, 0x50, 0x60, 0xc9, 0x29, 0xa3, 0x82, 0xb7, 0x08, 0x96, 0x0c, 0xa4,
	0xf2, 0x56, 0x2f, 0x10, 0x81, 0x9c, 0xb5, 0x56, 0x8c, 0xe7, 0xe6, 0xb4, 0xc1, 0x28, 0xf6, 0x5e,
	0xc3, 0x8d, 0x9d, 0x30, 0x13, 0x74, 0x90, 0x19, 0xe3, 0x9f, 0x8f, 0x79, 0x26, 0x70, 0x01, 0xda,
	0xa9, 0x8c, 0xf7, 0xb2, 0xf0, 0xab, 0xde, 0x66, 0xb3, 0x71, 0x95, 0x78, 0x2b, 0x63, 0x5c, 0x04,
	0xa0, 0xa2, 0x48, 0x0e, 0x79, 0x9c, 0xf3, 0xa5, 0xf6, 0x77, 0x2a, 0xe1, 0x1d, 0x00, 0x8e, 0x02,
	0x66, 0xa9, 0xbc, 0xda, 0x5c, 0x5d, 0x07, 0xcd, 0x8c, 0x08, 0x8c, 0x5c, 0x07, 0xea, 0x63, 0x79,
	0x11, 0x1f, 0xc2, 0x54, 0xcc, 0xbf, 0x88, 0xbd, 0xda, 0x82, 0x49, 0x95, 0xde, 0x2d, 0x97, 0xdc,
	0x83, 0xa9, 0x97, 0x5c, 0xef, 0x28, 0x38, 0x57, 0xfe, 0x10, 0xde, 0x3a, 0xe0, 0xe6, 0x90, 0x07,
	0x82, 0x5f, 0xea, 0xba, 0x0f, 0x36, 0xad, 0xa2, 0xc6, 0x1a, 0x0d, 0x5d, 0xf3, 0xb6, 0x01, 0xdf,
	0xa7, 0xbd, 0xea, 0x68, 0xf5, 0x1f, 0x57, 0x42, 0x99, 0x57, 0x40, 0x2d, 0x03, 0xbe, 0xe0, 0x11,
	0xbf, 0x1a, 0x6a, 0xed, 0xb7, 0x05, 0x8e, 0x36, 0x0c, 0xdf, 0x40, 0x4b, 0xd9, 0x87, 0xe5, 0x0d,
	0xac, 0x9d, 0x8e, 0xeb, 0x36, 0x95, 0xb4, 0xcf, 0x1e, 0xfe, 0xf8, 0x73, 0xfe, 0xcb, 0xbc, 0x86,
	0xe0, 0x9f, 0xac, 0xe6, 0xaf, 0x0f, 0xee, 0x80, 0x25, 0xcd, 0xc2, 0xb9, 0x62, 0xac, 0xe2, 0x9c,
	0x7b, 0x99, 0xb9, 0xb7, 0x48, 0x10, 0x73, 0x78, 0xeb, 0x02, 0xc2, 0xff, 0x46, 0xbf, 0xf2, 0x6d,
	0xf9, 0x8e, 0xaf, 0xc0, 0xd1, 0xbe, 0x62, 0xc9, 0xa3, 0xee, 0x73, 0x15, 0x73, 0x9e, 0x30, 0x67,
	0xbc, 0x11, 0x5a, 0x1b, 0xda, 0x21, 0xfc, 0x00, 0x8e, 0x36, 0xfb, 0x02, 0xaf, 0x6e, 0x7e, 0x15,
	0x6f, 0x99, 0xf0, 0xee, 0xb8, 0xcd, 0x1c, 0x0b, 0xe8, 0x8f, 0xe0, 0x68, 0xf3, 0x2f, 0xa0, 0xeb,
	0x87, 0xe1, 0xce, 0x76, 0xf5, 0x8b, 0xdb, 0x2d, 0x5e, 0xdc, 0xee, 0x96, 0x7a, 0x71, 0x0b, 0x1f,
	0x1e, 0x35, 0xef, 0xd8, 0x77, 0xa8, 0xfd, 0xc9, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x95, 0xb8,
	0xec, 0x56, 0xeb, 0x05, 0x00, 0x00,
}
