/**
 * @fileoverview
 * @enhanceable
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var geometry_geometry_pb = require('../geometry/geometry_pb.js');
goog.exportSymbol('proto.computation_renders.ComputationRenderRequest', null, global);
goog.exportSymbol('proto.computation_renders.ComputationRenderResponse', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.computation_renders.ComputationRenderRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.computation_renders.ComputationRenderRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.computation_renders.ComputationRenderRequest.displayName = 'proto.computation_renders.ComputationRenderRequest';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.computation_renders.ComputationRenderRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.computation_renders.ComputationRenderRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.computation_renders.ComputationRenderRequest} msg The msg instance to transform.
 * @return {!Object}
 */
proto.computation_renders.ComputationRenderRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    operatorKey: jspb.Message.getFieldWithDefault(msg, 1, ""),
    time: +jspb.Message.getFieldWithDefault(msg, 2, 0.0),
    boundingBox: (f = msg.getBoundingBox()) && geometry_geometry_pb.BoundingBox2D.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.computation_renders.ComputationRenderRequest}
 */
proto.computation_renders.ComputationRenderRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.computation_renders.ComputationRenderRequest;
  return proto.computation_renders.ComputationRenderRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.computation_renders.ComputationRenderRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.computation_renders.ComputationRenderRequest}
 */
proto.computation_renders.ComputationRenderRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setOperatorKey(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setTime(value);
      break;
    case 3:
      var value = new geometry_geometry_pb.BoundingBox2D;
      reader.readMessage(value,geometry_geometry_pb.BoundingBox2D.deserializeBinaryFromReader);
      msg.setBoundingBox(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.computation_renders.ComputationRenderRequest} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.computation_renders.ComputationRenderRequest.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.computation_renders.ComputationRenderRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.computation_renders.ComputationRenderRequest.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getOperatorKey();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = this.getTime();
  if (f !== 0.0) {
    writer.writeDouble(
      2,
      f
    );
  }
  f = this.getBoundingBox();
  if (f != null) {
    writer.writeMessage(
      3,
      f,
      geometry_geometry_pb.BoundingBox2D.serializeBinaryToWriter
    );
  }
};


/**
 * optional string operator_key = 1;
 * @return {string}
 */
proto.computation_renders.ComputationRenderRequest.prototype.getOperatorKey = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.computation_renders.ComputationRenderRequest.prototype.setOperatorKey = function(value) {
  jspb.Message.setField(this, 1, value);
};


/**
 * optional double time = 2;
 * @return {number}
 */
proto.computation_renders.ComputationRenderRequest.prototype.getTime = function() {
  return /** @type {number} */ (+jspb.Message.getFieldWithDefault(this, 2, 0.0));
};


/** @param {number} value */
proto.computation_renders.ComputationRenderRequest.prototype.setTime = function(value) {
  jspb.Message.setField(this, 2, value);
};


/**
 * optional geometry.BoundingBox2D bounding_box = 3;
 * @return {?proto.geometry.BoundingBox2D}
 */
proto.computation_renders.ComputationRenderRequest.prototype.getBoundingBox = function() {
  return /** @type{?proto.geometry.BoundingBox2D} */ (
    jspb.Message.getWrapperField(this, geometry_geometry_pb.BoundingBox2D, 3));
};


/** @param {?proto.geometry.BoundingBox2D|undefined} value */
proto.computation_renders.ComputationRenderRequest.prototype.setBoundingBox = function(value) {
  jspb.Message.setWrapperField(this, 3, value);
};


proto.computation_renders.ComputationRenderRequest.prototype.clearBoundingBox = function() {
  this.setBoundingBox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.computation_renders.ComputationRenderRequest.prototype.hasBoundingBox = function() {
  return jspb.Message.getField(this, 3) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.computation_renders.ComputationRenderResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.computation_renders.ComputationRenderResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.computation_renders.ComputationRenderResponse.displayName = 'proto.computation_renders.ComputationRenderResponse';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.computation_renders.ComputationRenderResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.computation_renders.ComputationRenderResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.computation_renders.ComputationRenderResponse} msg The msg instance to transform.
 * @return {!Object}
 */
proto.computation_renders.ComputationRenderResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    resourceId: jspb.Message.getFieldWithDefault(msg, 1, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.computation_renders.ComputationRenderResponse}
 */
proto.computation_renders.ComputationRenderResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.computation_renders.ComputationRenderResponse;
  return proto.computation_renders.ComputationRenderResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.computation_renders.ComputationRenderResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.computation_renders.ComputationRenderResponse}
 */
proto.computation_renders.ComputationRenderResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setResourceId(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Class method variant: serializes the given message to binary data
 * (in protobuf wire format), writing to the given BinaryWriter.
 * @param {!proto.computation_renders.ComputationRenderResponse} message
 * @param {!jspb.BinaryWriter} writer
 */
proto.computation_renders.ComputationRenderResponse.serializeBinaryToWriter = function(message, writer) {
  message.serializeBinaryToWriter(writer);
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.computation_renders.ComputationRenderResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  this.serializeBinaryToWriter(writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the message to binary data (in protobuf wire format),
 * writing to the given BinaryWriter.
 * @param {!jspb.BinaryWriter} writer
 */
proto.computation_renders.ComputationRenderResponse.prototype.serializeBinaryToWriter = function (writer) {
  var f = undefined;
  f = this.getResourceId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
};


/**
 * optional string resource_id = 1;
 * @return {string}
 */
proto.computation_renders.ComputationRenderResponse.prototype.getResourceId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/** @param {string} value */
proto.computation_renders.ComputationRenderResponse.prototype.setResourceId = function(value) {
  jspb.Message.setField(this, 1, value);
};


goog.object.extend(exports, proto.computation_renders);
