// Code generated by protoc-gen-go. DO NOT EDIT.
// source: scenes/scenes.proto

/*
Package scenes is a generated protocol buffer package.

It is generated from these files:
	scenes/scenes.proto

It has these top-level messages:
	Scene
	ListScenesRequest
	ListScenesResponse
	GetSceneRequest
	CreateSceneRequest
	DeleteSceneRequest
	RenameSceneRequest
*/
package scenes

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import google_protobuf1 "github.com/golang/protobuf/ptypes/empty"
import operators "github.com/stupschwartz/qubit/proto-gen/go/operators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Scene struct {
	Id          string                           `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	ProjectId   string                           `protobuf:"bytes,2,opt,name=project_id,json=projectId" json:"project_id,omitempty"`
	Version     int32                            `protobuf:"varint,3,opt,name=version" json:"version,omitempty"`
	Name        string                           `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Operators   map[string]*operators.Operator   `protobuf:"bytes,5,rep,name=operators" json:"operators,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Connections map[string]*operators.Connection `protobuf:"bytes,6,rep,name=connections" json:"connections,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Scene) Reset()                    { *m = Scene{} }
func (m *Scene) String() string            { return proto.CompactTextString(m) }
func (*Scene) ProtoMessage()               {}
func (*Scene) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Scene) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scene) GetProjectId() string {
	if m != nil {
		return m.ProjectId
	}
	return ""
}

func (m *Scene) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *Scene) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Scene) GetOperators() map[string]*operators.Operator {
	if m != nil {
		return m.Operators
	}
	return nil
}

func (m *Scene) GetConnections() map[string]*operators.Connection {
	if m != nil {
		return m.Connections
	}
	return nil
}

type ListScenesRequest struct {
	PageSize  int32  `protobuf:"varint,1,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`
	PageToken string `protobuf:"bytes,2,opt,name=page_token,json=pageToken" json:"page_token,omitempty"`
}

func (m *ListScenesRequest) Reset()                    { *m = ListScenesRequest{} }
func (m *ListScenesRequest) String() string            { return proto.CompactTextString(m) }
func (*ListScenesRequest) ProtoMessage()               {}
func (*ListScenesRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ListScenesRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ListScenesRequest) GetPageToken() string {
	if m != nil {
		return m.PageToken
	}
	return ""
}

type ListScenesResponse struct {
	Scenes        []*Scene `protobuf:"bytes,1,rep,name=scenes" json:"scenes,omitempty"`
	NextPageToken string   `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken" json:"next_page_token,omitempty"`
}

func (m *ListScenesResponse) Reset()                    { *m = ListScenesResponse{} }
func (m *ListScenesResponse) String() string            { return proto.CompactTextString(m) }
func (*ListScenesResponse) ProtoMessage()               {}
func (*ListScenesResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ListScenesResponse) GetScenes() []*Scene {
	if m != nil {
		return m.Scenes
	}
	return nil
}

func (m *ListScenesResponse) GetNextPageToken() string {
	if m != nil {
		return m.NextPageToken
	}
	return ""
}

type GetSceneRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetSceneRequest) Reset()                    { *m = GetSceneRequest{} }
func (m *GetSceneRequest) String() string            { return proto.CompactTextString(m) }
func (*GetSceneRequest) ProtoMessage()               {}
func (*GetSceneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type CreateSceneRequest struct {
	Scene *Scene `protobuf:"bytes,1,opt,name=scene" json:"scene,omitempty"`
}

func (m *CreateSceneRequest) Reset()                    { *m = CreateSceneRequest{} }
func (m *CreateSceneRequest) String() string            { return proto.CompactTextString(m) }
func (*CreateSceneRequest) ProtoMessage()               {}
func (*CreateSceneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *CreateSceneRequest) GetScene() *Scene {
	if m != nil {
		return m.Scene
	}
	return nil
}

type DeleteSceneRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *DeleteSceneRequest) Reset()                    { *m = DeleteSceneRequest{} }
func (m *DeleteSceneRequest) String() string            { return proto.CompactTextString(m) }
func (*DeleteSceneRequest) ProtoMessage()               {}
func (*DeleteSceneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *DeleteSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type RenameSceneRequest struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
}

func (m *RenameSceneRequest) Reset()                    { *m = RenameSceneRequest{} }
func (m *RenameSceneRequest) String() string            { return proto.CompactTextString(m) }
func (*RenameSceneRequest) ProtoMessage()               {}
func (*RenameSceneRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *RenameSceneRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RenameSceneRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*Scene)(nil), "scenes.Scene")
	proto.RegisterType((*ListScenesRequest)(nil), "scenes.ListScenesRequest")
	proto.RegisterType((*ListScenesResponse)(nil), "scenes.ListScenesResponse")
	proto.RegisterType((*GetSceneRequest)(nil), "scenes.GetSceneRequest")
	proto.RegisterType((*CreateSceneRequest)(nil), "scenes.CreateSceneRequest")
	proto.RegisterType((*DeleteSceneRequest)(nil), "scenes.DeleteSceneRequest")
	proto.RegisterType((*RenameSceneRequest)(nil), "scenes.RenameSceneRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Scenes service

type ScenesClient interface {
	List(ctx context.Context, in *ListScenesRequest, opts ...grpc.CallOption) (*ListScenesResponse, error)
	Get(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*Scene, error)
	Create(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*Scene, error)
	Delete(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error)
	Rename(ctx context.Context, in *RenameSceneRequest, opts ...grpc.CallOption) (*Scene, error)
}

type scenesClient struct {
	cc *grpc.ClientConn
}

func NewScenesClient(cc *grpc.ClientConn) ScenesClient {
	return &scenesClient{cc}
}

func (c *scenesClient) List(ctx context.Context, in *ListScenesRequest, opts ...grpc.CallOption) (*ListScenesResponse, error) {
	out := new(ListScenesResponse)
	err := grpc.Invoke(ctx, "/scenes.Scenes/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenesClient) Get(ctx context.Context, in *GetSceneRequest, opts ...grpc.CallOption) (*Scene, error) {
	out := new(Scene)
	err := grpc.Invoke(ctx, "/scenes.Scenes/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenesClient) Create(ctx context.Context, in *CreateSceneRequest, opts ...grpc.CallOption) (*Scene, error) {
	out := new(Scene)
	err := grpc.Invoke(ctx, "/scenes.Scenes/Create", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenesClient) Delete(ctx context.Context, in *DeleteSceneRequest, opts ...grpc.CallOption) (*google_protobuf1.Empty, error) {
	out := new(google_protobuf1.Empty)
	err := grpc.Invoke(ctx, "/scenes.Scenes/Delete", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *scenesClient) Rename(ctx context.Context, in *RenameSceneRequest, opts ...grpc.CallOption) (*Scene, error) {
	out := new(Scene)
	err := grpc.Invoke(ctx, "/scenes.Scenes/Rename", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Scenes service

type ScenesServer interface {
	List(context.Context, *ListScenesRequest) (*ListScenesResponse, error)
	Get(context.Context, *GetSceneRequest) (*Scene, error)
	Create(context.Context, *CreateSceneRequest) (*Scene, error)
	Delete(context.Context, *DeleteSceneRequest) (*google_protobuf1.Empty, error)
	Rename(context.Context, *RenameSceneRequest) (*Scene, error)
}

func RegisterScenesServer(s *grpc.Server, srv ScenesServer) {
	s.RegisterService(&_Scenes_serviceDesc, srv)
}

func _Scenes_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListScenesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenesServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scenes.Scenes/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenesServer).List(ctx, req.(*ListScenesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenes_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenesServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scenes.Scenes/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenesServer).Get(ctx, req.(*GetSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenes_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenesServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scenes.Scenes/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenesServer).Create(ctx, req.(*CreateSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenes_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenesServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scenes.Scenes/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenesServer).Delete(ctx, req.(*DeleteSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Scenes_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameSceneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ScenesServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/scenes.Scenes/Rename",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ScenesServer).Rename(ctx, req.(*RenameSceneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Scenes_serviceDesc = grpc.ServiceDesc{
	ServiceName: "scenes.Scenes",
	HandlerType: (*ScenesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _Scenes_List_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Scenes_Get_Handler,
		},
		{
			MethodName: "Create",
			Handler:    _Scenes_Create_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Scenes_Delete_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _Scenes_Rename_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "scenes/scenes.proto",
}

func init() { proto.RegisterFile("scenes/scenes.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 585 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x7c, 0x54, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0x56, 0xe3, 0xd8, 0x90, 0x09, 0x6d, 0xda, 0x89, 0x68, 0x1d, 0xb7, 0x40, 0x31, 0x14, 0x15,
	0x90, 0x6c, 0x11, 0x2e, 0x25, 0x27, 0xa4, 0x52, 0x10, 0x12, 0xa2, 0xd4, 0xa5, 0x17, 0x2e, 0x91,
	0x9b, 0x0c, 0x91, 0x69, 0x6a, 0x1b, 0x7b, 0x13, 0x11, 0x10, 0x17, 0xce, 0xdc, 0x78, 0x07, 0x5e,
	0x88, 0x57, 0xe0, 0x41, 0xf0, 0xee, 0xfa, 0x27, 0xb6, 0x2b, 0x4e, 0xd9, 0x9d, 0x9f, 0xef, 0xfb,
	0xe6, 0xdb, 0x89, 0xa1, 0x1b, 0x8f, 0xc8, 0xa7, 0xd8, 0x96, 0x3f, 0x56, 0x18, 0x05, 0x2c, 0x40,
	0x4d, 0xde, 0x8c, 0x9d, 0x49, 0x10, 0x4c, 0xa6, 0x64, 0xbb, 0xa1, 0x67, 0xbb, 0xbe, 0x1f, 0x30,
	0x97, 0x79, 0x81, 0x9f, 0x56, 0x19, 0xdb, 0x69, 0x56, 0xdc, 0xce, 0x67, 0x1f, 0x6d, 0xba, 0x0c,
	0xd9, 0x22, 0x4d, 0xf6, 0x82, 0x90, 0x22, 0x97, 0x05, 0x51, 0x6c, 0xe7, 0x27, 0x99, 0x32, 0x7f,
	0x2a, 0xa0, 0x9e, 0x72, 0x02, 0x5c, 0x83, 0x86, 0x37, 0xd6, 0x57, 0x76, 0x57, 0xf6, 0x5b, 0x4e,
	0x72, 0xc2, 0x5b, 0x00, 0x49, 0xc9, 0x27, 0x1a, 0xb1, 0x61, 0x12, 0x6f, 0x88, 0x78, 0x2b, 0x8d,
	0xbc, 0x1e, 0xa3, 0x0e, 0xd7, 0xe6, 0x14, 0xc5, 0x89, 0x04, 0x5d, 0x49, 0x72, 0xaa, 0x93, 0x5d,
	0x11, 0xa1, 0xe9, 0xbb, 0x97, 0xa4, 0x37, 0x45, 0x8b, 0x38, 0xe3, 0x00, 0x5a, 0x39, 0xb3, 0xae,
	0xee, 0x2a, 0xfb, 0xed, 0xfe, 0x8e, 0x95, 0x8e, 0x29, 0xe8, 0xad, 0xe3, 0x2c, 0x7d, 0xe4, 0xb3,
	0x68, 0xe1, 0x14, 0xe5, 0xf8, 0x1c, 0xda, 0xa3, 0xc0, 0xf7, 0x13, 0x5a, 0x3e, 0xaf, 0xae, 0x89,
	0xee, 0xdb, 0xe5, 0xee, 0xc3, 0xa2, 0x40, 0xf6, 0x2f, 0xb7, 0x18, 0x27, 0xb0, 0x56, 0x86, 0xc7,
	0x75, 0x50, 0x2e, 0x68, 0x91, 0x4e, 0xcb, 0x8f, 0xf8, 0x10, 0xd4, 0xb9, 0x3b, 0x9d, 0x91, 0x98,
	0xb4, 0xdd, 0xef, 0x5a, 0x85, 0x53, 0x59, 0xaf, 0x23, 0x2b, 0x06, 0x8d, 0x83, 0x15, 0xe3, 0x0c,
	0xd6, 0xab, 0x9c, 0x57, 0x80, 0x3e, 0x2e, 0x83, 0xde, 0x5c, 0x02, 0x2d, 0xba, 0x97, 0x60, 0xcd,
	0x63, 0xd8, 0x78, 0xe3, 0xc5, 0x4c, 0x0c, 0x15, 0x3b, 0xf4, 0x79, 0x46, 0x31, 0xc3, 0x6d, 0x68,
	0x85, 0xee, 0x84, 0x86, 0xb1, 0xf7, 0x95, 0x04, 0xba, 0xea, 0x5c, 0xe7, 0x81, 0xd3, 0xe4, 0x2e,
	0x9e, 0x89, 0x27, 0x59, 0x70, 0x41, 0x7e, 0xfe, 0x4c, 0x49, 0xe4, 0x3d, 0x0f, 0x98, 0x23, 0xc0,
	0x65, 0xc0, 0x38, 0x4c, 0xd4, 0x12, 0xee, 0x41, 0xba, 0x55, 0x09, 0x1c, 0x77, 0x73, 0xb5, 0xe4,
	0xa6, 0x93, 0x26, 0xf1, 0x01, 0x74, 0x7c, 0xfa, 0xc2, 0x86, 0x35, 0x82, 0x55, 0x1e, 0x7e, 0x97,
	0x93, 0xdc, 0x85, 0xce, 0x2b, 0x92, 0x1c, 0x99, 0xe6, 0xca, 0x36, 0x99, 0xcf, 0x00, 0x0f, 0x23,
	0x72, 0x19, 0x95, 0xaa, 0xee, 0x81, 0x2a, 0xa8, 0x44, 0x61, 0x4d, 0x86, 0xcc, 0x99, 0xf7, 0x01,
	0x5f, 0xd0, 0x94, 0x2a, 0xad, 0x55, 0x82, 0x03, 0x40, 0x87, 0xf8, 0xae, 0xfd, 0xaf, 0x2a, 0xdf,
	0xcd, 0x46, 0xb1, 0x9b, 0xfd, 0xdf, 0x0a, 0x68, 0xd2, 0x1f, 0x3c, 0x81, 0x26, 0x77, 0x0b, 0x7b,
	0x99, 0x90, 0xda, 0x63, 0x18, 0xc6, 0x55, 0x29, 0x69, 0xab, 0x89, 0x3f, 0xfe, 0xfc, 0xfd, 0xd5,
	0xb8, 0x81, 0x60, 0xcf, 0x9f, 0xa4, 0x7f, 0x62, 0x7c, 0x09, 0x4a, 0xe2, 0x0d, 0x6e, 0x65, 0x6d,
	0x15, 0xa3, 0x8c, 0xf2, 0xcc, 0xe6, 0x96, 0x80, 0xd8, 0xc0, 0x4e, 0x01, 0x61, 0x7f, 0xf3, 0xc6,
	0xdf, 0xf1, 0x2d, 0x68, 0xd2, 0x40, 0xcc, 0x15, 0xd4, 0x0d, 0xad, 0xa2, 0xf5, 0x04, 0x5a, 0xd7,
	0x5c, 0x12, 0x34, 0x90, 0xae, 0xe2, 0x19, 0x68, 0xd2, 0xd5, 0x02, 0xaf, 0xee, 0xb2, 0xb1, 0x69,
	0xc9, 0xef, 0x8a, 0x95, 0x7d, 0x57, 0xac, 0x23, 0xfe, 0x5d, 0xc9, 0x64, 0x3e, 0xaa, 0xc9, 0xfc,
	0x00, 0x9a, 0x7c, 0x86, 0x02, 0xb6, 0xfe, 0x2c, 0x55, 0x99, 0x7b, 0x02, 0xed, 0x8e, 0xb9, 0x59,
	0x41, 0xb3, 0x23, 0xd1, 0x9a, 0x4a, 0x3e, 0xd7, 0x84, 0x88, 0xa7, 0xff, 0x02, 0x00, 0x00, 0xff,
	0xff, 0x08, 0x2c, 0xb9, 0x03, 0x27, 0x05, 0x00, 0x00,
}
