// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute/compute.proto

/*
Package compute is a generated protocol buffer package.

It is generated from these files:
	compute/compute.proto

It has these top-level messages:
	RenderImageRequest
	RenderImageResponse
*/
package compute

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import geometry "github.com/stupschwartz/qubit/proto-gen/go/geometry"
import images "github.com/stupschwartz/qubit/proto-gen/go/images"
import operators "github.com/stupschwartz/qubit/proto-gen/go/operators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RenderImageRequest struct {
	Operator    *operators.Operator     `protobuf:"bytes,1,opt,name=operator" json:"operator,omitempty"`
	BoundingBox *geometry.BoundingBox2D `protobuf:"bytes,2,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
}

func (m *RenderImageRequest) Reset()                    { *m = RenderImageRequest{} }
func (m *RenderImageRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderImageRequest) ProtoMessage()               {}
func (*RenderImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RenderImageRequest) GetOperator() *operators.Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *RenderImageRequest) GetBoundingBox() *geometry.BoundingBox2D {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

type RenderImageResponse struct {
	ImagePlane *images.Plane `protobuf:"bytes,1,opt,name=image_plane,json=imagePlane" json:"image_plane,omitempty"`
}

func (m *RenderImageResponse) Reset()                    { *m = RenderImageResponse{} }
func (m *RenderImageResponse) String() string            { return proto.CompactTextString(m) }
func (*RenderImageResponse) ProtoMessage()               {}
func (*RenderImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RenderImageResponse) GetImagePlane() *images.Plane {
	if m != nil {
		return m.ImagePlane
	}
	return nil
}

func init() {
	proto.RegisterType((*RenderImageRequest)(nil), "compute.RenderImageRequest")
	proto.RegisterType((*RenderImageResponse)(nil), "compute.RenderImageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compute service

type ComputeClient interface {
	RenderImage(ctx context.Context, in *RenderImageRequest, opts ...grpc.CallOption) (*RenderImageResponse, error)
}

type computeClient struct {
	cc *grpc.ClientConn
}

func NewComputeClient(cc *grpc.ClientConn) ComputeClient {
	return &computeClient{cc}
}

func (c *computeClient) RenderImage(ctx context.Context, in *RenderImageRequest, opts ...grpc.CallOption) (*RenderImageResponse, error) {
	out := new(RenderImageResponse)
	err := grpc.Invoke(ctx, "/compute.Compute/RenderImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Compute service

type ComputeServer interface {
	RenderImage(context.Context, *RenderImageRequest) (*RenderImageResponse, error)
}

func RegisterComputeServer(s *grpc.Server, srv ComputeServer) {
	s.RegisterService(&_Compute_serviceDesc, srv)
}

func _Compute_RenderImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServer).RenderImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compute.Compute/RenderImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServer).RenderImage(ctx, req.(*RenderImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Compute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compute.Compute",
	HandlerType: (*ComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderImage",
			Handler:    _Compute_RenderImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute/compute.proto",
}

func init() { proto.RegisterFile("compute/compute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 241 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0xb1, 0x4e, 0xc3, 0x30,
	0x10, 0x25, 0x0c, 0x14, 0x9d, 0x61, 0x71, 0x84, 0x5a, 0x02, 0x03, 0xca, 0xc4, 0x64, 0x4b, 0x61,
	0x63, 0x2c, 0x30, 0xc0, 0x02, 0xb2, 0xc4, 0x5c, 0xc5, 0xf4, 0x14, 0x55, 0x22, 0x3e, 0x63, 0x3b,
	0x52, 0x19, 0xf9, 0x73, 0x54, 0xdb, 0x49, 0x41, 0x30, 0xf9, 0xdd, 0xdd, 0x7b, 0xd6, 0x7b, 0x0f,
	0xce, 0xde, 0xa8, 0xb7, 0x43, 0x40, 0x99, 0x5f, 0x61, 0x1d, 0x05, 0xe2, 0xb3, 0x3c, 0x56, 0xf3,
	0x0e, 0xa9, 0xc7, 0xe0, 0x3e, 0xe5, 0x08, 0x12, 0xa3, 0x2a, 0x37, 0x7d, 0xdb, 0xa1, 0x97, 0xe9,
	0xc9, 0xcb, 0x73, 0xb2, 0xe8, 0xda, 0x40, 0xce, 0xcb, 0x09, 0xa5, 0x53, 0xfd, 0x55, 0x00, 0x57,
	0x68, 0xd6, 0xe8, 0x1e, 0x77, 0x0a, 0x85, 0x1f, 0x03, 0xfa, 0xc0, 0x25, 0x1c, 0x8f, 0xcc, 0x45,
	0x71, 0x55, 0x5c, 0xb3, 0xa6, 0x14, 0x7b, 0xe9, 0x73, 0x46, 0x6a, 0x22, 0xf1, 0x5b, 0x38, 0xd1,
	0x34, 0x98, 0xf5, 0xc6, 0x74, 0x2b, 0x4d, 0xdb, 0xc5, 0x61, 0x14, 0xcd, 0xc5, 0x64, 0x6f, 0x99,
	0xaf, 0x4b, 0xda, 0x36, 0xf7, 0x8a, 0xe9, 0xfd, 0x58, 0x3f, 0x40, 0xf9, 0xcb, 0x82, 0xb7, 0x64,
	0x3c, 0x72, 0x01, 0x2c, 0xa6, 0x58, 0xd9, 0xf7, 0xd6, 0x60, 0xb6, 0x71, 0x2a, 0x72, 0xb2, 0x97,
	0xdd, 0x52, 0x41, 0x9c, 0x22, 0x6e, 0x5e, 0x61, 0x76, 0x97, 0xea, 0xe1, 0x4f, 0xc0, 0x7e, 0xfc,
	0xc8, 0x2f, 0xc4, 0x58, 0xe3, 0xdf, 0xa8, 0xd5, 0xe5, 0xff, 0xc7, 0x64, 0xa2, 0x3e, 0xd0, 0x47,
	0xb1, 0xa8, 0x9b, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x64, 0xb7, 0x3b, 0xbd, 0x93, 0x01, 0x00,
	0x00,
}
