// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compute/compute.proto

/*
Package compute is a generated protocol buffer package.

It is generated from these files:
	compute/compute.proto

It has these top-level messages:
	RenderImageRequest
	RenderImageResponse
*/
package compute

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import geometry "github.com/stupschwartz/qubit/proto-gen/go/geometry"
import images "github.com/stupschwartz/qubit/proto-gen/go/images"
import operators "github.com/stupschwartz/qubit/proto-gen/go/operators"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// BoundingBox2D from public import geometry/geometry.proto
type BoundingBox2D geometry.BoundingBox2D

func (m *BoundingBox2D) Reset()           { (*geometry.BoundingBox2D)(m).Reset() }
func (m *BoundingBox2D) String() string   { return (*geometry.BoundingBox2D)(m).String() }
func (*BoundingBox2D) ProtoMessage()      {}
func (m *BoundingBox2D) GetStartX() int32 { return (*geometry.BoundingBox2D)(m).GetStartX() }
func (m *BoundingBox2D) GetStartY() int32 { return (*geometry.BoundingBox2D)(m).GetStartY() }
func (m *BoundingBox2D) GetEndX() int32   { return (*geometry.BoundingBox2D)(m).GetEndX() }
func (m *BoundingBox2D) GetEndY() int32   { return (*geometry.BoundingBox2D)(m).GetEndY() }

// Image from public import images/images.proto
type Image images.Image

func (m *Image) Reset()                     { (*images.Image)(m).Reset() }
func (m *Image) String() string             { return (*images.Image)(m).String() }
func (*Image) ProtoMessage()                {}
func (m *Image) GetId() string              { return (*images.Image)(m).GetId() }
func (m *Image) GetImageSequenceId() string { return (*images.Image)(m).GetImageSequenceId() }
func (m *Image) GetName() string            { return (*images.Image)(m).GetName() }
func (m *Image) GetWidth() int32            { return (*images.Image)(m).GetWidth() }
func (m *Image) GetHeight() int32           { return (*images.Image)(m).GetHeight() }
func (m *Image) GetLabels() map[string]string {
	o := (*images.Image)(m).GetLabels()
	if o == nil {
		return nil
	}
	s := make(map[string]string, len(o))
	for k, v := range o {
		s[k] = (string)(v)
	}
	return s
}
func (m *Image) GetPlanes() []*Plane {
	o := (*images.Image)(m).GetPlanes()
	if o == nil {
		return nil
	}
	s := make([]*Plane, len(o))
	for i, x := range o {
		s[i] = (*Plane)(x)
	}
	return s
}

// Plane from public import images/images.proto
type Plane images.Plane

func (m *Plane) Reset()           { (*images.Plane)(m).Reset() }
func (m *Plane) String() string   { return (*images.Plane)(m).String() }
func (*Plane) ProtoMessage()      {}
func (m *Plane) GetName() string  { return (*images.Plane)(m).GetName() }
func (m *Plane) GetWidth() int32  { return (*images.Plane)(m).GetWidth() }
func (m *Plane) GetHeight() int32 { return (*images.Plane)(m).GetHeight() }
func (m *Plane) GetLabels() map[string]string {
	o := (*images.Plane)(m).GetLabels()
	if o == nil {
		return nil
	}
	s := make(map[string]string, len(o))
	for k, v := range o {
		s[k] = (string)(v)
	}
	return s
}
func (m *Plane) GetChannels() []*Channel {
	o := (*images.Plane)(m).GetChannels()
	if o == nil {
		return nil
	}
	s := make([]*Channel, len(o))
	for i, x := range o {
		s[i] = (*Channel)(x)
	}
	return s
}

// Channel from public import images/images.proto
type Channel images.Channel

func (m *Channel) Reset()          { (*images.Channel)(m).Reset() }
func (m *Channel) String() string  { return (*images.Channel)(m).String() }
func (*Channel) ProtoMessage()     {}
func (m *Channel) GetName() string { return (*images.Channel)(m).GetName() }
func (m *Channel) GetRows() []*Row {
	o := (*images.Channel)(m).GetRows()
	if o == nil {
		return nil
	}
	s := make([]*Row, len(o))
	for i, x := range o {
		s[i] = (*Row)(x)
	}
	return s
}

// Row from public import images/images.proto
type Row images.Row

func (m *Row) Reset()             { (*images.Row)(m).Reset() }
func (m *Row) String() string     { return (*images.Row)(m).String() }
func (*Row) ProtoMessage()        {}
func (m *Row) GetData() []float64 { return (*images.Row)(m).GetData() }

// ListImagesRequest from public import images/images.proto
type ListImagesRequest images.ListImagesRequest

func (m *ListImagesRequest) Reset()             { (*images.ListImagesRequest)(m).Reset() }
func (m *ListImagesRequest) String() string     { return (*images.ListImagesRequest)(m).String() }
func (*ListImagesRequest) ProtoMessage()        {}
func (m *ListImagesRequest) GetPageSize() int32 { return (*images.ListImagesRequest)(m).GetPageSize() }
func (m *ListImagesRequest) GetPageToken() string {
	return (*images.ListImagesRequest)(m).GetPageToken()
}

// ListImagesResponse from public import images/images.proto
type ListImagesResponse images.ListImagesResponse

func (m *ListImagesResponse) Reset()         { (*images.ListImagesResponse)(m).Reset() }
func (m *ListImagesResponse) String() string { return (*images.ListImagesResponse)(m).String() }
func (*ListImagesResponse) ProtoMessage()    {}
func (m *ListImagesResponse) GetImages() []*Image {
	o := (*images.ListImagesResponse)(m).GetImages()
	if o == nil {
		return nil
	}
	s := make([]*Image, len(o))
	for i, x := range o {
		s[i] = (*Image)(x)
	}
	return s
}
func (m *ListImagesResponse) GetNextPageToken() string {
	return (*images.ListImagesResponse)(m).GetNextPageToken()
}

// GetImageRequest from public import images/images.proto
type GetImageRequest images.GetImageRequest

func (m *GetImageRequest) Reset()         { (*images.GetImageRequest)(m).Reset() }
func (m *GetImageRequest) String() string { return (*images.GetImageRequest)(m).String() }
func (*GetImageRequest) ProtoMessage()    {}
func (m *GetImageRequest) GetId() string  { return (*images.GetImageRequest)(m).GetId() }

// CreateImageRequest from public import images/images.proto
type CreateImageRequest images.CreateImageRequest

func (m *CreateImageRequest) Reset()         { (*images.CreateImageRequest)(m).Reset() }
func (m *CreateImageRequest) String() string { return (*images.CreateImageRequest)(m).String() }
func (*CreateImageRequest) ProtoMessage()    {}
func (m *CreateImageRequest) GetImage() *Image {
	return (*Image)((*images.CreateImageRequest)(m).GetImage())
}

// UpdateImageRequest from public import images/images.proto
type UpdateImageRequest images.UpdateImageRequest

func (m *UpdateImageRequest) Reset()         { (*images.UpdateImageRequest)(m).Reset() }
func (m *UpdateImageRequest) String() string { return (*images.UpdateImageRequest)(m).String() }
func (*UpdateImageRequest) ProtoMessage()    {}
func (m *UpdateImageRequest) GetId() string  { return (*images.UpdateImageRequest)(m).GetId() }
func (m *UpdateImageRequest) GetImage() *Image {
	return (*Image)((*images.UpdateImageRequest)(m).GetImage())
}

// DeleteImageRequest from public import images/images.proto
type DeleteImageRequest images.DeleteImageRequest

func (m *DeleteImageRequest) Reset()         { (*images.DeleteImageRequest)(m).Reset() }
func (m *DeleteImageRequest) String() string { return (*images.DeleteImageRequest)(m).String() }
func (*DeleteImageRequest) ProtoMessage()    {}
func (m *DeleteImageRequest) GetId() string  { return (*images.DeleteImageRequest)(m).GetId() }

// Component from public import operators/operators.proto
type Component operators.Component

func (m *Component) Reset()            { (*operators.Component)(m).Reset() }
func (m *Component) String() string    { return (*operators.Component)(m).String() }
func (*Component) ProtoMessage()       {}
func (m *Component) GetName() string   { return (*operators.Component)(m).GetName() }
func (m *Component) GetValue() float64 { return (*operators.Component)(m).GetValue() }

// Parameter from public import operators/operators.proto
type Parameter operators.Parameter

func (m *Parameter) Reset()          { (*operators.Parameter)(m).Reset() }
func (m *Parameter) String() string  { return (*operators.Parameter)(m).String() }
func (*Parameter) ProtoMessage()     {}
func (m *Parameter) GetName() string { return (*operators.Parameter)(m).GetName() }
func (m *Parameter) GetLabels() map[string]string {
	o := (*operators.Parameter)(m).GetLabels()
	if o == nil {
		return nil
	}
	s := make(map[string]string, len(o))
	for k, v := range o {
		s[k] = (string)(v)
	}
	return s
}
func (m *Parameter) GetComponents() []*Component {
	o := (*operators.Parameter)(m).GetComponents()
	if o == nil {
		return nil
	}
	s := make([]*Component, len(o))
	for i, x := range o {
		s[i] = (*Component)(x)
	}
	return s
}

// Operator from public import operators/operators.proto
type Operator operators.Operator

func (m *Operator) Reset()              { (*operators.Operator)(m).Reset() }
func (m *Operator) String() string      { return (*operators.Operator)(m).String() }
func (*Operator) ProtoMessage()         {}
func (m *Operator) GetId() string       { return (*operators.Operator)(m).GetId() }
func (m *Operator) GetSceneId() string  { return (*operators.Operator)(m).GetSceneId() }
func (m *Operator) GetType() string     { return (*operators.Operator)(m).GetType() }
func (m *Operator) GetName() string     { return (*operators.Operator)(m).GetName() }
func (m *Operator) GetContext() string  { return (*operators.Operator)(m).GetContext() }
func (m *Operator) GetInputs() []string { return (*operators.Operator)(m).GetInputs() }
func (m *Operator) GetParameters() []*Parameter {
	o := (*operators.Operator)(m).GetParameters()
	if o == nil {
		return nil
	}
	s := make([]*Parameter, len(o))
	for i, x := range o {
		s[i] = (*Parameter)(x)
	}
	return s
}

// ListOperatorsRequest from public import operators/operators.proto
type ListOperatorsRequest operators.ListOperatorsRequest

func (m *ListOperatorsRequest) Reset()         { (*operators.ListOperatorsRequest)(m).Reset() }
func (m *ListOperatorsRequest) String() string { return (*operators.ListOperatorsRequest)(m).String() }
func (*ListOperatorsRequest) ProtoMessage()    {}
func (m *ListOperatorsRequest) GetPageSize() int32 {
	return (*operators.ListOperatorsRequest)(m).GetPageSize()
}
func (m *ListOperatorsRequest) GetPageToken() string {
	return (*operators.ListOperatorsRequest)(m).GetPageToken()
}

// ListOperatorsResponse from public import operators/operators.proto
type ListOperatorsResponse operators.ListOperatorsResponse

func (m *ListOperatorsResponse) Reset()         { (*operators.ListOperatorsResponse)(m).Reset() }
func (m *ListOperatorsResponse) String() string { return (*operators.ListOperatorsResponse)(m).String() }
func (*ListOperatorsResponse) ProtoMessage()    {}
func (m *ListOperatorsResponse) GetOperators() []*Operator {
	o := (*operators.ListOperatorsResponse)(m).GetOperators()
	if o == nil {
		return nil
	}
	s := make([]*Operator, len(o))
	for i, x := range o {
		s[i] = (*Operator)(x)
	}
	return s
}
func (m *ListOperatorsResponse) GetNextPageToken() string {
	return (*operators.ListOperatorsResponse)(m).GetNextPageToken()
}

// GetOperatorRequest from public import operators/operators.proto
type GetOperatorRequest operators.GetOperatorRequest

func (m *GetOperatorRequest) Reset()         { (*operators.GetOperatorRequest)(m).Reset() }
func (m *GetOperatorRequest) String() string { return (*operators.GetOperatorRequest)(m).String() }
func (*GetOperatorRequest) ProtoMessage()    {}
func (m *GetOperatorRequest) GetId() string  { return (*operators.GetOperatorRequest)(m).GetId() }

// CreateOperatorRequest from public import operators/operators.proto
type CreateOperatorRequest operators.CreateOperatorRequest

func (m *CreateOperatorRequest) Reset()         { (*operators.CreateOperatorRequest)(m).Reset() }
func (m *CreateOperatorRequest) String() string { return (*operators.CreateOperatorRequest)(m).String() }
func (*CreateOperatorRequest) ProtoMessage()    {}
func (m *CreateOperatorRequest) GetOperator() *Operator {
	return (*Operator)((*operators.CreateOperatorRequest)(m).GetOperator())
}

// UpdateOperatorRequest from public import operators/operators.proto
type UpdateOperatorRequest operators.UpdateOperatorRequest

func (m *UpdateOperatorRequest) Reset()         { (*operators.UpdateOperatorRequest)(m).Reset() }
func (m *UpdateOperatorRequest) String() string { return (*operators.UpdateOperatorRequest)(m).String() }
func (*UpdateOperatorRequest) ProtoMessage()    {}
func (m *UpdateOperatorRequest) GetId() string  { return (*operators.UpdateOperatorRequest)(m).GetId() }
func (m *UpdateOperatorRequest) GetOperator() *Operator {
	return (*Operator)((*operators.UpdateOperatorRequest)(m).GetOperator())
}

// DeleteOperatorRequest from public import operators/operators.proto
type DeleteOperatorRequest operators.DeleteOperatorRequest

func (m *DeleteOperatorRequest) Reset()         { (*operators.DeleteOperatorRequest)(m).Reset() }
func (m *DeleteOperatorRequest) String() string { return (*operators.DeleteOperatorRequest)(m).String() }
func (*DeleteOperatorRequest) ProtoMessage()    {}
func (m *DeleteOperatorRequest) GetId() string  { return (*operators.DeleteOperatorRequest)(m).GetId() }

// RenderOperatorRequest from public import operators/operators.proto
type RenderOperatorRequest operators.RenderOperatorRequest

func (m *RenderOperatorRequest) Reset()         { (*operators.RenderOperatorRequest)(m).Reset() }
func (m *RenderOperatorRequest) String() string { return (*operators.RenderOperatorRequest)(m).String() }
func (*RenderOperatorRequest) ProtoMessage()    {}
func (m *RenderOperatorRequest) GetId() string  { return (*operators.RenderOperatorRequest)(m).GetId() }
func (m *RenderOperatorRequest) GetFrame() int32 {
	return (*operators.RenderOperatorRequest)(m).GetFrame()
}

// RenderOperatorResponse from public import operators/operators.proto
type RenderOperatorResponse operators.RenderOperatorResponse

func (m *RenderOperatorResponse) Reset() { (*operators.RenderOperatorResponse)(m).Reset() }
func (m *RenderOperatorResponse) String() string {
	return (*operators.RenderOperatorResponse)(m).String()
}
func (*RenderOperatorResponse) ProtoMessage() {}
func (m *RenderOperatorResponse) GetResultUrl() string {
	return (*operators.RenderOperatorResponse)(m).GetResultUrl()
}
func (m *RenderOperatorResponse) GetResultType() string {
	return (*operators.RenderOperatorResponse)(m).GetResultType()
}

type RenderImageRequest struct {
	Operator    *operators.Operator     `protobuf:"bytes,1,opt,name=operator" json:"operator,omitempty"`
	Parameters  []*operators.Parameter  `protobuf:"bytes,2,rep,name=parameters" json:"parameters,omitempty"`
	BoundingBox *geometry.BoundingBox2D `protobuf:"bytes,3,opt,name=bounding_box,json=boundingBox" json:"bounding_box,omitempty"`
}

func (m *RenderImageRequest) Reset()                    { *m = RenderImageRequest{} }
func (m *RenderImageRequest) String() string            { return proto.CompactTextString(m) }
func (*RenderImageRequest) ProtoMessage()               {}
func (*RenderImageRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RenderImageRequest) GetOperator() *operators.Operator {
	if m != nil {
		return m.Operator
	}
	return nil
}

func (m *RenderImageRequest) GetParameters() []*operators.Parameter {
	if m != nil {
		return m.Parameters
	}
	return nil
}

func (m *RenderImageRequest) GetBoundingBox() *geometry.BoundingBox2D {
	if m != nil {
		return m.BoundingBox
	}
	return nil
}

type RenderImageResponse struct {
	ImagePlane *images.Plane `protobuf:"bytes,1,opt,name=image_plane,json=imagePlane" json:"image_plane,omitempty"`
}

func (m *RenderImageResponse) Reset()                    { *m = RenderImageResponse{} }
func (m *RenderImageResponse) String() string            { return proto.CompactTextString(m) }
func (*RenderImageResponse) ProtoMessage()               {}
func (*RenderImageResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *RenderImageResponse) GetImagePlane() *images.Plane {
	if m != nil {
		return m.ImagePlane
	}
	return nil
}

func init() {
	proto.RegisterType((*RenderImageRequest)(nil), "compute.RenderImageRequest")
	proto.RegisterType((*RenderImageResponse)(nil), "compute.RenderImageResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Compute service

type ComputeClient interface {
	RenderImage(ctx context.Context, in *RenderImageRequest, opts ...grpc.CallOption) (*RenderImageResponse, error)
}

type computeClient struct {
	cc *grpc.ClientConn
}

func NewComputeClient(cc *grpc.ClientConn) ComputeClient {
	return &computeClient{cc}
}

func (c *computeClient) RenderImage(ctx context.Context, in *RenderImageRequest, opts ...grpc.CallOption) (*RenderImageResponse, error) {
	out := new(RenderImageResponse)
	err := grpc.Invoke(ctx, "/compute.Compute/RenderImage", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Compute service

type ComputeServer interface {
	RenderImage(context.Context, *RenderImageRequest) (*RenderImageResponse, error)
}

func RegisterComputeServer(s *grpc.Server, srv ComputeServer) {
	s.RegisterService(&_Compute_serviceDesc, srv)
}

func _Compute_RenderImage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenderImageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComputeServer).RenderImage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compute.Compute/RenderImage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComputeServer).RenderImage(ctx, req.(*RenderImageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Compute_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compute.Compute",
	HandlerType: (*ComputeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RenderImage",
			Handler:    _Compute_RenderImage_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compute/compute.proto",
}

func init() { proto.RegisterFile("compute/compute.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x6c, 0x50, 0x31, 0x4f, 0xf3, 0x30,
	0x10, 0x6d, 0x5a, 0xe9, 0xeb, 0xa7, 0x0b, 0x2c, 0x0e, 0xa8, 0x21, 0x30, 0x54, 0x99, 0x98, 0x1c,
	0x29, 0x30, 0x31, 0x16, 0x18, 0x60, 0x21, 0xb2, 0xc4, 0x5c, 0x25, 0xf4, 0x14, 0x55, 0x22, 0x39,
	0x63, 0x3b, 0x52, 0xf9, 0x65, 0xfc, 0x3d, 0x5a, 0xdb, 0x49, 0x83, 0x60, 0xf2, 0xbb, 0x7b, 0xef,
	0x25, 0xef, 0x1e, 0x9c, 0xbf, 0x51, 0x23, 0x3b, 0x83, 0x99, 0x7f, 0xb9, 0x54, 0x64, 0x88, 0xcd,
	0xfd, 0x98, 0x2c, 0x6a, 0xa4, 0x06, 0x8d, 0xfa, 0xcc, 0x7a, 0xe0, 0x14, 0x49, 0xb4, 0x6d, 0xca,
	0x1a, 0x75, 0xe6, 0x1e, 0xbf, 0xbc, 0x20, 0x89, 0xaa, 0x34, 0xa4, 0x74, 0x36, 0x20, 0x47, 0xa5,
	0x5f, 0x01, 0x30, 0x81, 0xed, 0x06, 0xd5, 0xd3, 0xc1, 0x21, 0xf0, 0xa3, 0x43, 0x6d, 0x58, 0x06,
	0xff, 0x7b, 0x65, 0x1c, 0x2c, 0x83, 0xeb, 0x30, 0x8f, 0xf8, 0xd1, 0xfa, 0xe2, 0x91, 0x18, 0x44,
	0xec, 0x16, 0x40, 0x96, 0xaa, 0xdc, 0x47, 0x41, 0xa5, 0xe3, 0xe9, 0x72, 0xb6, 0xb7, 0x9c, 0x8d,
	0x2c, 0x45, 0x4f, 0x8a, 0x91, 0x8e, 0xdd, 0xc1, 0x49, 0x45, 0x5d, 0xbb, 0xd9, 0xb6, 0xf5, 0xba,
	0xa2, 0x5d, 0x3c, 0xb3, 0xbf, 0x5a, 0xf0, 0xe1, 0xa8, 0x95, 0x67, 0x57, 0xb4, 0xcb, 0x1f, 0x44,
	0x58, 0x1d, 0xc7, 0xf4, 0x11, 0xa2, 0x1f, 0xc1, 0xb5, 0xa4, 0x56, 0x23, 0xe3, 0x10, 0xda, 0xdb,
	0xd7, 0xf2, 0xbd, 0x6c, 0xd1, 0x87, 0x3f, 0xe5, 0xbe, 0x8f, 0xe2, 0xb0, 0x14, 0x60, 0x27, 0x8b,
	0xf3, 0x57, 0x98, 0xdf, 0xbb, 0x52, 0xd9, 0x33, 0x84, 0xa3, 0x2f, 0xb2, 0x4b, 0xde, 0x97, 0xff,
	0xbb, 0xa0, 0xe4, 0xea, 0x6f, 0xd2, 0x85, 0x48, 0x27, 0xc5, 0xa4, 0x08, 0x8a, 0x69, 0xf5, 0xcf,
	0x96, 0x7c, 0xf3, 0x1d, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x42, 0xcb, 0x01, 0xcf, 0x01, 0x00, 0x00,
}
