apiVersion: v1
kind: Service
metadata:
  name: compute-esp
spec:
  ports:
  # Port that accepts gRPC and JSON/HTTP2 requests over HTTP.
  - port: 80
    targetPort: 9000
    protocol: TCP
    name: http2
  selector:
    app: compute-esp
  type: LoadBalancer
